import {useEffect,useState} from 'react';
import {Input,Table,Select} from 'antd';
import NarrativePanel from './NarrativePanel';
import Chart from './Chart';
import FocusAnalysis from './FocusAnalysis';
import { api, fmt, pct } from './api';
import {cleanText,periodLabel,displayNumber} from './presentation';
const colors = ['#087f88', '#729bc2', '#d69a48', '#aa7cb1', '#be694b', '#75a98b'];
// 接口字段名 → 业务可读表头（未收录的键原样显示，不隐藏数据）
const KEY_LABELS: Record<string, string> = {
    factory: '工厂', product_name: '产品名称', product: '产品', specification: '产品规格', month: '月份',
    quantity: '产量', material_name: '原材料名称', unit_material_cost: '单位消耗成本(元/盒)', total_material_cost: '原材料总成本(元)',
    share: '占比', expense_category: '费用类别', unit_expense: '单位费用(元/盒)', total_expense: '费用总额(元)',
    total_labor: '直接人工总额(元)', total_hours: '总工时(小时)', workers: '生产人数(人)', working_days: '工作天数(天)',
    name: '名称', unit: '单位', previous: '上期', current: '本期', delta: '变动额', rate: '变动率', value: '数值',
};
export function DataTable({ rows, empty = '暂无可用明细' }: { rows: any[]; empty?: string }) {
 const [query,setQuery]=useState('');
 if(!rows?.length)return <p className="empty">{empty}</p>;
 const keys=Object.keys(rows[0]).filter(key=>!['source_hash','row_key','metric_refs','evidence_refs','hash','snapshot_id'].includes(key)&&!key.startsWith('_'));
 const filtered=rows.filter(row=>!query||keys.some(key=>String(row[key]??'').toLowerCase().includes(query.toLowerCase())));
 const columns=keys.map(key=>({title:KEY_LABELS[key]??key,dataIndex:key,key,align:rows.some(row=>row[key]!=null)&&rows.filter(row=>row[key]!=null&&row[key]!=='').every(row=>Number.isFinite(Number(row[key])))?'right' as const:'left' as const,sorter:(a:any,b:any)=>{const av=a[key],bv=b[key];return av!=null&&bv!=null&&Number.isFinite(Number(av))&&Number.isFinite(Number(bv))?Number(av)-Number(bv):String(av??'').localeCompare(String(bv??''),'zh-CN')},render:(value:any)=>typeof value==='object'&&value!==null?'附属记录，请查看原文件':typeof value==='number'?displayNumber(value):cleanText(value??'未提供')}));
 return <div className="data-table">{rows.length>12&&<Input.Search aria-label="筛选表格记录" placeholder="搜索表格内容" allowClear value={query} onChange={event=>setQuery(event.target.value)} style={{maxWidth:280,marginBottom:12}}/>}<Table size="small" columns={columns} dataSource={filtered.map((row,index)=>({...row,_table_key:index}))} rowKey="_table_key" scroll={{x:'max-content'}} pagination={filtered.length>12?{pageSize:12,showSizeChanger:false,showTotal:total=>`共 ${total} 条`}:false} locale={{emptyText:'未找到匹配记录'}}/></div>;
}
export function Details({ details }: {
    details: any;
    }) { return <section className="panel"><h2>原料与费用明细</h2>{!details?.available ? <p className="notice">{details?.reason ?? '该工厂未提供可下钻明细，不能按比例推算。'}</p> : <><p className="muted">原料与费用明细按原文件的计量单位呈现；市场行情不能替代企业采购单价或实物耗量。</p>{[['materials', '原料'], ['expenses', '制造费用'], ['labor', '人工'], ['market', '市场参考']].map(([k, title]) => <details key={k} open={k === 'materials'}><summary>{title}明细</summary><DataTable rows={details[k]}/></details>)}</>}</section>; }
export default function Analysis({ snapshot, basis, onEvidence }: {
    snapshot: any;
    basis: 'unit' | 'total';
    onEvidence: (v: any) => void;
}) {
    const [comparisonKey,setComparisonKey]=useState<'mom'|'yoy'|'budget'>('mom');
    // 成本预测（赛题加分项）：随快照获取 Holt 外推结果，趋势图叠加虚线预测与实验性波动范围。
    const [forecast,setForecast]=useState<any>(null);
    useEffect(()=>{const c=new AbortController();setForecast(null);
        const p=new URLSearchParams({context_id:snapshot.context_id,factory:snapshot.factory,product:snapshot.product,month:snapshot.month,analysis_type:snapshot.analysis_type,basis});
        api(`/forecast?${p}`,undefined,c.signal).then(x=>{if(!c.signal.aborted)setForecast(x)}).catch(e=>{if(!c.signal.aborted)setForecast({status:'ERROR',reason:`预测加载失败：${e instanceof Error?e.message:String(e)}`})});
        return()=>c.abort()},[snapshot.snapshot_id,basis]);
    const fp=forecast?.status==='PASS'?(forecast.points??[]):[];
    // 确定性根因定位（2026-09-22 方法论落地）：多维归因+DiD+价格信号，程序计算。
    const [attrib,setAttrib]=useState<any>(null);
    useEffect(()=>{const c=new AbortController();setAttrib(null);
        const p=new URLSearchParams({context_id:snapshot.context_id,factory:snapshot.factory,product:snapshot.product,month:snapshot.month,basis,analysis_type:snapshot.analysis_type});
        api(`/attribution?${p}`,undefined,c.signal).then(x=>{if(!c.signal.aborted)setAttrib(x)}).catch(e=>{if(!c.signal.aborted)setAttrib({status:'ERROR',reason:`归因加载失败：${e instanceof Error?e.message:String(e)}`})});
        return()=>c.abort()},[snapshot.snapshot_id,basis]);
    const m = snapshot.metrics, elements = snapshot.elements ?? [], t = snapshot.trend ?? [], isUnit = basis === 'unit', comp = snapshot.comparison?.[comparisonKey], start = Number(comp?.base ?? 0), end = Number(comp?.current ?? 0);
    const quantityUnit = m.quantity?.unit ?? snapshot.quantity_unit ?? '盒', currency = m.total_cost?.unit ?? snapshot.currency ?? '元', unitLabel = m.unit_cost?.unit ?? `${currency}/${quantityUnit}`, costLabel = isUnit ? unitLabel : currency;
    let acc = start;
    const changes = elements.map((e: any) => Number(e.comparisons?.[comparisonKey]?.[basis]?.delta ?? (comparisonKey==='mom'?e.delta:0) ?? 0));
    const bottoms = changes.map((n: number) => { const b = Math.min(acc, acc + n); acc += n; return b; });
    const waterfall = comp?.base === null || comp?.base === undefined ? null : { tooltip: { trigger: 'axis', formatter:(p:any[])=>{const i=p[0].dataIndex; const v=i===0?start:i===changes.length+1?end:changes[i-1]; if(v===null||v===undefined)return `${p[0].axisValue}：无可比期`; return `${p[0].axisValue}：${i>0&&i<=changes.length&&v>=0?'+':''}${fmt(v)} ${costLabel}`;} }, grid: { left: 58, right: 20, top: 25, bottom: 40 }, xAxis: { type: 'category', data: [({mom:'上期',yoy:'去年同期',budget:'预算'})[comparisonKey], ...elements.map((e: any) => e.name), '本期'] }, yAxis: { type: 'value', min: (value: { min: number }) => (value.min >= 0 ? 0 : undefined), name: costLabel }, series: [{ type: 'bar', stack: 'cost', silent: true, itemStyle: { color: 'transparent' }, data: [0, ...bottoms, 0] }, { type: 'bar', stack: 'cost', barMaxWidth: 46, data: [{ value: start, itemStyle: { color: '#9eafb9' } }, ...changes.map((x: number | null) => x === null ? null : { value: Math.abs(x), itemStyle: { color: x >= 0 ? '#bd673f' : '#75a98b' } }), { value: end, itemStyle: { color: '#227c81' } }], label: { show: true, position: 'top', formatter: (p: any) => p.dataIndex === 0 ? fmt(start) : p.dataIndex === changes.length + 1 ? fmt(end) : changes[p.dataIndex-1] === null ? '—' : `${changes[p.dataIndex-1]>=0?'+':''}${fmt(changes[p.dataIndex-1])}` } }] };
    return <>
 <section id="g-overview" className="workbench-group"><div className="metrics">{[[isUnit ? '单位成本' : '总成本', isUnit ? m.unit_cost : m.total_cost, false], ['环比', m.mom, true], ['同比', m.yoy, true], ['预算偏差', m.budget, true]].map(([label, metric, percent]: any) => <button className="metric" key={label} onClick={() => onEvidence({...metric,product:snapshot.product,factory:snapshot.factory,period:snapshot.period})}><span>{label}</span><strong className={percent && Number(metric?.value) > 0 ? 'increase' : percent && Number(metric?.value) < 0 ? 'decrease' : ''}>{percent ? pct(metric?.value) : fmt(metric?.value)}<small>{!percent ? metric?.unit : ''}</small></strong><em>{metric?.reason ?? (metric?.comparison_period ? `比较期 ${periodLabel(metric.comparison_period)}` : '点击查看计算口径与来源')}</em></button>)}</div>
 <p className="snapshot-line">{snapshot.product} · {snapshot.factory} · {snapshot.period?.start === snapshot.period?.end ? snapshot.period?.end : `${snapshot.period?.start} 至 ${snapshot.period?.end}`} · 产量 {fmt(m.quantity?.value, 0)} {quantityUnit}</p></section>
 <section id="g-trend" className="workbench-group"><div className="chart-grid trend-layout"><section className="panel"><div className="panel-heading"><h2>{isUnit ? '单位成本' : '总成本'}趋势{fp.length?'与预测':''}</h2><span>{t[0]?.month} 至 {t.at(-1)?.month} · 可用 {t.length} 个月{fp.length?` · 预测 ${fp.length} 个月`:''}</span></div><Chart label="成本趋势图" option={{ color: ['#087f88','#b87931'], legend: { data: fp.length ? ['历史','预测'] : ['历史'], bottom: 0 }, tooltip: { trigger: 'axis', formatter:(ps:any[])=>ps.filter(p=>!String(p.seriesName).includes('区间')).map(p=>`${p.marker}${p.seriesName}：${p.value==null?'—':fmt(p.value)} ${costLabel}`).join('\n') }, grid: { left: 60, right: 20, top: 30, bottom: fp.length?60:35 }, xAxis: { type: 'category', data: [...t.map((r: any) => r.month),...fp.map((p: any) => p.month)] }, yAxis: { type: 'value', min: ({min, max}: any) => Math.max(0, +(min - (max - min) * 0.25).toFixed(2)), name: costLabel }, series: [{ name:'历史', type: 'line', data: [...t.map((r: any) => (isUnit ? r.unit_cost : r.total_cost)==null?null:Number(isUnit ? r.unit_cost : r.total_cost)),...fp.map(()=>null)], symbolSize: 7, lineStyle: { width: 3 }, areaStyle: { opacity: 0.06 } }, ...(fp.length?[{ name:'预测', type:'line' as const, data:[...t.map(()=>null),...fp.map((p:any)=>p.point)], symbol:'diamond', symbolSize:8, lineStyle:{width:2,type:'dashed'}, itemStyle:{color:'#b87931'} },
        { name:'区间底', type:'line' as const, stack:'band', data:[...t.map(()=>null),...fp.map((p:any)=>p.low)], lineStyle:{width:0}, symbol:'none', silent:true, itemStyle:{color:'transparent'}, legendHoverLink:false },
        { name:'预测区间', type:'line' as const, stack:'band', data:[...t.map(()=>null),...fp.map((p:any)=>Number((p.high-p.low).toFixed(4)))], lineStyle:{width:0}, symbol:'none', silent:true, areaStyle:{color:'rgba(232,179,108,0.18)'}, itemStyle:{color:'transparent'}, legendHoverLink:false }]:[]) ] }}/><details><summary>查看精确趋势数据</summary><DataTable rows={t.map((r: any) => ({ '月份': r.month, [`单位成本(${unitLabel})`]: r.unit_cost, [`总成本(${currency})`]: r.total_cost, [`产量(${quantityUnit})`]: r.quantity }))}/></details></section>
 <section className="panel"><h2>成本结构</h2><Chart label="成本要素结构图" option={{ color: colors, tooltip: { trigger: 'item', formatter:(p:any)=>`${p.name}：${fmt(p.value)} ${costLabel}（${fmt(p.percent)}%）` }, legend: { bottom: 4 }, series: [{ type: 'pie', radius: ['48%', '70%'], center: ['50%', '44%'], label: { show: true, formatter:'{b}\n{d}%' }, data: elements.map((e: any) => ({ name: e.name, value: Number(isUnit ? e.unit : e.total) })) }] }}/></section><section className="panel"><h2>成本要素明细</h2><div className="table-scroll"><table><thead><tr><th>成本要素</th><th>本期（{costLabel}）</th><th>变动额</th><th>贡献度</th></tr></thead><tbody>{elements.map((e:any)=><tr key={e.key}><td>{e.name}</td><td>{fmt(isUnit ? e.unit : e.total)}</td><td>{fmt(e.comparisons?.mom?.[basis]?.delta ?? e.delta)}</td><td>{pct(e.comparisons?.mom?.[basis]?.contribution ?? e.contribution)}</td></tr>)}</tbody></table></div><p className="muted">按本期与上期可比口径；无比较基期时显示缺项。</p></section></div>
 <details className="panel forecast-disclosure"><summary>查看下月预测与历史检验</summary>{forecast&&(forecast.status==='PASS'?<section className="panel"><div className="panel-heading"><h2>下月成本预测</h2><span>{forecast.method}</span></div><div className="table-scroll"><table><thead><tr><th>月份</th><th>点预测（{costLabel}）</th><th>朴素基线</th><th>实验性波动范围下限</th><th>实验性波动范围上限</th></tr></thead><tbody>{fp.map((p:any)=><tr key={p.month}><td>{p.month}</td><td>{fmt(p.point)}{p.negative_warning?'（外推为负，趋势异常需人工核对）':''}</td><td>{fmt(forecast.baseline?.points?.find((b:any)=>b.month===p.month)?.point)}</td><td>{fmt(p.low)}</td><td>{fmt(p.high)}</td></tr>)}</tbody></table></div>
        {forecast.series?.length>1&&<details><summary>分要素预测（{isUnit?'单位成本':'总成本'}口径）</summary><DataTable rows={forecast.series.filter((s:any)=>s.status==='PASS').flatMap((s:any)=>s.points.map((p:any)=>({'序列':s.label,'月份':p.month,'点预测':fmt(p.point),'下限':fmt(p.low),'上限':fmt(p.high)})))}/></details>}
        <p className="muted">{forecast.evaluation_notice} · 一步平均绝对误差：Holt {fmt(forecast.one_step_mae,4)}，上期值基线 {fmt(forecast.baseline?.one_step_mae,4)}。不代表未来覆盖率已验证。</p><p className="muted">历史 {forecast.history_months?.[0]} 至 {forecast.history_months?.[1]} · 残差σ {fmt(forecast.residual_std,4)} · {forecast.interval}。{forecast.caveat}</p></section>:forecast.status==='ERROR'?<section className="panel"><h2>下月成本预测</h2><p className="error" role="alert">{forecast.reason}</p></section>:<section className="panel"><h2>下月成本预测</h2><p className="notice">{forecast.reason??'历史观测不足，不输出预测。'}</p></section>)}</details>
 </section>
 <section id="g-focus" className="workbench-group"><FocusAnalysis focus={snapshot.focus}/>
 <section className="panel" aria-label="根因定位"><div className="panel-heading"><h2>需要关注 · 原因核查优先级</h2><span>按当前分析期间与成本口径计算，供人工核查</span></div>

 {attrib?.status==='PASS'?<><p className="muted">{attrib.factory} · {attrib.product} · {attrib.month} 对 {attrib.base_month}（{attrib.basis==='unit'?'单位成本':'总成本'}口径）：总变动 <strong>{attrib.total_delta}</strong>（{attrib.direction}）。要素贡献反映成本变动构成；排序是核查优先级，不是因果概率。</p>
 <div className="table-scroll"><table><thead><tr><th>排序</th><th>候选原因</th><th>变动贡献/参考</th><th>方向</th><th>核查优先级</th><th>依据</th></tr></thead><tbody>
 {attrib.ranking?.map((r:any,i:number)=><tr key={i}><td>{i+1}</td><td>{r.cause}</td><td>{r.ep_pct}</td><td>{r.direction}</td><td>{r.label}（{r.score}）</td><td style={{whiteSpace:'normal'}}>{r.basis}</td></tr>)}
 {attrib.did?.status==='PASS'&&<tr><td>附</td><td>跨厂前后变化对照（{attrib.did.control}）</td><td>{attrib.did.tau} 元/盒</td><td>—</td><td>前提尚待核验</td><td style={{whiteSpace:'normal'}}>安慰剂τ={attrib.did.placebo_tau??'未检'}；估计值，{attrib.did.assumption}</td></tr>}
 </tbody></table></div>
 {attrib.price_signal?.status==='PASS'&&attrib.price_signal.materials?.some((m:any)=>m.consistent)&&<p className="muted" style={{marginTop:8}}>行情变化参考：{attrib.price_signal.materials.filter((m:any)=>m.consistent).map((m:any)=>`${m.name}（市场价${m.market_change_pct} 与单位材料成本${m.unit_change_pct} 同向）`).join('、')}；行情同向幅度参考 {attrib.price_signal.aggregate_price_explained_pct}（不能作为因果解释比例或精确价量分解）。</p>}
 </>:attrib?.status==='ERROR'?<p className="error" role="alert">{attrib.reason}</p>:<p className="notice">{attrib?.reason??'当前选择无可用根因定位（需要摄取型成本数据与完整基期）。'}</p>}
 </section></section>
 <details id="g-bridge" className="panel workbench-collapse"><summary><h2>成本变动拆解 · 本期比上期差在哪</h2><span>与上期/去年同期/预算逐项对比的瀑布图，原料涨价贡献排序与要素热力图</span></summary>
 <section className="panel"><div className="panel-heading"><h2>{snapshot.product} · {snapshot.factory} · {snapshot.period?.end} 成本变动</h2><Select aria-label="桥接比较口径" value={comparisonKey} onChange={setComparisonKey} options={[{value:'mom',label:'环比'},{value:'yoy',label:'同比'},{value:'budget',label:'预算'}]} style={{minWidth:100}}/><span>{isUnit ? '单位成本变动' : '总额变动，包含产量影响'}</span></div>{waterfall ? <Chart label="成本要素变动瀑布图" option={waterfall}/> : <p className="empty">N/A · {comp?.reason ?? '没有完整可比上期，不能生成桥接'}</p>}<div className="table-scroll"><table><thead><tr><th>成本要素</th><th>单位成本（{unitLabel}）</th><th>总额（{currency}）</th><th>变动额（{costLabel}）</th><th>贡献度</th><th>去年同期（{unitLabel}）</th><th>单位同比</th><th>单位环比</th><th>总额环比</th></tr></thead><tbody>{elements.map((e: any) => <tr key={e.key}><td>{e.name}</td><td>{fmt(e.unit)}</td><td>{fmt(e.total)}</td><td>{fmt(e.comparisons?.[comparisonKey]?.[basis]?.delta ?? (comparisonKey==='mom'?e.delta:null))}</td><td>{pct(e.comparisons?.[comparisonKey]?.[basis]?.contribution ?? (comparisonKey==='mom'?e.contribution:null))}</td><td>{fmt(e.comparisons?.yoy?.unit?.base ?? snapshot.period_values?.yoy?.elements_unit?.[e.key])}</td><td>{pct(e.comparisons?.yoy?.unit?.rate)}</td><td className={e.alerts?.unit ? 'increase' : ''}>{pct(e.unit_mom)} {e.alerts?.unit ? '重点分析' : ''}</td><td className={e.alerts?.total ? 'increase' : ''}>{pct(e.total_mom)} {e.alerts?.total ? '重点分析' : ''}</td></tr>)}</tbody></table></div><p className="muted">告警：各成本要素环比严格超过 ±10%。恰好 ±10% 不触发；负贡献及超过 100% 均保留。总额受单位成本和产量共同影响。</p></section>
 {snapshot.budget_bridge && <section className="panel"><h2>预算差异来源拆解 · 产量与单位成本各影响多少</h2><DataTable rows={[{ '产量影响(元)': snapshot.budget_bridge.quantity_effect, '单位成本影响(元)': snapshot.budget_bridge.unit_cost_effect, '总额差异(元)': snapshot.budget_bridge.total_delta }]}/><p className="muted">{snapshot.budget_bridge.formula}。{snapshot.budget_bridge.note}。</p></section>}{snapshot.materials_summary?.length>0&&<section className="panel"><h2>原料变动贡献排序</h2><p className="muted">{snapshot.product} · {snapshot.factory} · {snapshot.period?.end}；按原料每盒成本变动对材料增量的贡献排序。采购价与实物耗量尚须另行核查。</p><DataTable rows={snapshot.materials_summary.map((r:any)=>({'原料':r.name,'上期（元/盒）':fmt(r.previous),'本期（元/盒）':fmt(r.current),'差额（元/盒）':fmt(r.delta),'占材料增量':pct(r.contribution)}))}/></section>}<ElementHeatmap elements={elements}/>{snapshot.specialized_metrics && <section className="panel"><h2>行业专用指标</h2><DataTable rows={Array.isArray(snapshot.specialized_metrics)?snapshot.specialized_metrics.map((m:any)=>({'指标':m.name,'数值':m.value,'单位':m.unit,'口径':m.reason??String(m.formula??m.note??'见行业包策略定义').replaceAll('machine_hours','机时').replaceAll('energy_kwh','能耗')})):Object.entries(snapshot.specialized_metrics).map(([key,value])=>({指标:key,...(typeof value==='object'&&value!==null?value:{值:value})}))}/></section>}
 </details>
 <details id="g-drill" className="panel workbench-collapse"><summary><h2>原始明细查询 · 原料/费用/人工/行情</h2><span>当前期间的逐笔原始记录与市场价格参考</span></summary><Details details={snapshot.details}/></details>
 <section id="g-explain" className="workbench-group"><NarrativePanel snapshot={snapshot} onEvidence={onEvidence}/></section>
 <details id="g-industry" className="panel workbench-collapse"><summary><h2>行业参考数据 · 本厂处于什么水平</h2><span>题包提供的行业基准（静态数据），非所选月实测值，仅用于定位参考</span></summary>
 {snapshot.industry && <section className="panel"><h2>行业基准参考（静态）</h2><p>{snapshot.industry?.notice}</p><p>{snapshot.industry?.divisor?"规格换算后的单位成本":"当前数据单位成本"}：<strong>{fmt(snapshot.industry?.converted_unit_cost, 4)} {snapshot.industry?.unit}</strong>{snapshot.industry?.divisor?`（每${quantityUnit}成本 ÷ ${snapshot.industry.divisor}）`:"；未采用外部行业基准"}</p><DataTable rows={snapshot.industry?.rows ?? []}/></section>}
 </details>
 </>;
}

function ElementHeatmap({elements}:{elements:any[]}) {
 const data=elements.flatMap((e:any,y:number)=>[['单位成本',e.unit_mom],['总成本',e.total_mom]].flatMap(([,v],x)=>v===null||v===undefined||!Number.isFinite(Number(v))?[]:[[x,y,Number(v)]]));
 if(!data.length)return null;
 const bound=Math.max(10,...data.map((d:number[])=>Math.abs(d[2])));
 return <section className="panel"><h2>成本要素环比热力图</h2><p className="muted">当前期间与上期比较，单位为 %。无定义的变动留空；严格超过 ±10% 才触发重点分析。</p><Chart label="成本要素环比热力图" option={{tooltip:{formatter:(p:any)=>`${elements[p.value[1]].name} · ${p.value[0]===0?'单位成本':'总成本'}：${pct(p.value[2])}`},grid:{left:100,right:45,top:15,bottom:90},xAxis:{type:'category',data:['单位成本','总成本'],splitArea:{show:true}},yAxis:{type:'category',data:elements.map((e:any)=>e.name),splitArea:{show:true}},visualMap:{min:-bound,max:bound,orient:'horizontal',left:'center',bottom:5,inRange:{color:['#227c81','#f4f5ed','#bd673f']},formatter:(v:number)=>`${fmt(v,0)}%`},series:[{type:'heatmap',data,label:{show:true,formatter:(p:any)=>pct(p.value[2])}}]}}/></section>
}
