import {useState} from 'react';
import NarrativePanel from './NarrativePanel';
import Chart from './Chart';
import { fmt, pct } from './api';
import {cleanText} from './presentation';
const colors = ['#227c81', '#729bc2', '#e8b36c'];
export function DataTable({ rows, empty = '暂无可用明细' }: {
    rows: any[];
    empty?: string;
}) { if (!rows?.length)
    return <p className="empty">{empty}</p>; const keys = Object.keys(rows[0]).filter(k => !['source_hash', 'row_key', 'metric_refs', 'evidence_refs', 'hash', 'snapshot_id'].includes(k) && !k.startsWith('_')); return <div className="table-scroll"><table><thead><tr>{keys.map(k => <th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{keys.map(k => <td key={k}>{typeof r[k] === 'object' ? '详见机器审计附件' : cleanText(r[k] ?? '未提供')}</td>)}</tr>)}</tbody></table></div>; }
export function Details({ details }: {
    details: any;
}) { return <section className="panel"><h2>原料与费用下钻</h2>{!details?.available ? <p className="notice">{details?.reason ?? '该工厂未提供可下钻明细，不能按比例推算。'}</p> : <><p className="muted">原料单位消耗成本是元/盒；市场行情不能替代企业采购单价或实物耗量。</p>{[['materials', '原料'], ['expenses', '制造费用'], ['labor', '人工'], ['market', '市场参考']].map(([k, title]) => <details key={k} open={k === 'materials'}><summary>{title}明细</summary><DataTable rows={details[k]}/></details>)}</>}</section>; }
export default function Analysis({ snapshot, basis, onEvidence }: {
    snapshot: any;
    basis: 'unit' | 'total';
    onEvidence: (v: any) => void;
}) {
    const [comparisonKey,setComparisonKey]=useState<'mom'|'yoy'|'budget'>('mom');
    const m = snapshot.metrics, elements = snapshot.elements ?? [], t = snapshot.trend ?? [], isUnit = basis === 'unit', comp = snapshot.comparison?.[comparisonKey], start = Number(comp?.base ?? 0), end = Number(comp?.current ?? 0);
    let acc = start;
    const changes = elements.map((e: any) => Number(e.comparisons?.[comparisonKey]?.[basis]?.delta ?? (comparisonKey==='mom'?e.delta:0) ?? 0));
    const bottoms = changes.map((n: number) => { const b = Math.min(acc, acc + n); acc += n; return b; });
    const waterfall = comp?.base === null || comp?.base === undefined ? null : { tooltip: { trigger: 'axis', formatter:(p:any[])=>{const i=p[0].dataIndex; const v=i===0?start:i===changes.length+1?end:changes[i-1]; return `${p[0].axisValue}：${i>0&&i<=changes.length&&v>=0?'+':''}${fmt(v)} ${isUnit?'元/盒':'元'}`;} }, grid: { left: 58, right: 20, top: 25, bottom: 40 }, xAxis: { type: 'category', data: [({mom:'上期',yoy:'去年同期',budget:'预算'})[comparisonKey], ...elements.map((e: any) => e.name), '本期'] }, yAxis: { type: 'value', min: 0, name: isUnit ? '元/盒' : '元' }, series: [{ type: 'bar', stack: 'cost', silent: true, itemStyle: { color: 'transparent' }, data: [0, ...bottoms, 0] }, { type: 'bar', stack: 'cost', barMaxWidth: 46, data: [{ value: start, itemStyle: { color: '#9eafb9' } }, ...changes.map((x: number) => ({ value: Math.abs(x), itemStyle: { color: x >= 0 ? '#bd673f' : '#227c81' } })), { value: end, itemStyle: { color: '#227c81' } }], label: { show: true, position: 'top', formatter: (p: any) => p.dataIndex === 0 ? fmt(start) : p.dataIndex === changes.length + 1 ? fmt(end) : `${changes[p.dataIndex-1]>=0?'+':''}${fmt(changes[p.dataIndex-1])}` } }] };
    return <>
 <div className="metrics">{[[isUnit ? '单位成本' : '总成本', isUnit ? m.unit_cost : m.total_cost, false], ['环比', m.mom, true], ['同比', m.yoy, true], ['预算偏差', m.budget, true]].map(([label, metric, percent]: any) => <button className="metric" key={label} onClick={() => onEvidence({...metric,product:snapshot.product,factory:snapshot.factory,period:snapshot.period})}><span>{label}</span><strong className={percent && Number(metric?.value) > 0 ? 'increase' : ''}>{percent ? pct(metric?.value) : fmt(metric?.value)}<small>{!percent ? metric?.unit : ''}</small></strong><em>{metric?.reason ?? (metric?.comparison_period ? `比较期 ${Array.isArray(metric.comparison_period) ? metric.comparison_period.join(' 至 ') : metric.comparison_period}` : '点击查看计算口径与来源')}</em></button>)}</div>
 <p className="snapshot-line">{snapshot.product} · {snapshot.factory} · {snapshot.period?.start} 至 {snapshot.period?.end} · 产量 {fmt(m.quantity?.value, 0)} 盒</p>
 <div className="chart-grid"><section className="panel"><div className="panel-heading"><h2>{snapshot.product} · {snapshot.factory} 成本趋势</h2><span>{t[0]?.month} 至 {t.at(-1)?.month} · 可用 {t.length} 个月</span></div><Chart label="成本趋势图" option={{ color: ['#227c81'], tooltip: { trigger: 'axis' }, grid: { left: 60, right: 20, top: 30, bottom: 35 }, xAxis: { type: 'category', data: t.map((r: any) => r.month) }, yAxis: { type: 'value', min:0, name: isUnit ? '元/盒' : '元' }, series: [{ type: 'line', data: t.map((r: any) => Number(isUnit ? r.unit_cost : r.total_cost)), symbolSize: 7, lineStyle: { width: 3 }, areaStyle: { opacity: 0.06 } }] }}/><details><summary>查看精确趋势数据</summary><DataTable rows={t.map((r: any) => ({ '月份': r.month, '单位成本(元/盒)': r.unit_cost, '总成本(元)': r.total_cost, '产量(盒)': r.quantity }))}/></details></section>
 <section className="panel"><h2>{snapshot.product} · {snapshot.factory} · {snapshot.period?.end} 成本结构</h2><Chart label="三要素成本结构图" option={{ color: colors, tooltip: { trigger: 'item', formatter:(p:any)=>`${p.name}：${fmt(p.value)} ${isUnit?'元/盒':'元'}（${fmt(p.percent)}%）` }, legend: { bottom: 4 }, series: [{ type: 'pie', radius: ['48%', '70%'], center: ['50%', '44%'], label: { show: true, formatter:'{b}\n{d}%' }, data: elements.map((e: any) => ({ name: e.name, value: Number(isUnit ? e.unit : e.total) })) }] }}/></section></div>
 <section className="panel"><div className="panel-heading"><h2>{snapshot.product} · {snapshot.factory} · {snapshot.period?.end} 成本变动</h2><select aria-label="桥接比较口径" value={comparisonKey} onChange={e=>setComparisonKey(e.target.value as typeof comparisonKey)}><option value="mom">环比</option><option value="yoy">同比</option><option value="budget">预算</option></select><span>{isUnit ? '单位成本变动' : '总额变动，包含产量影响'}</span></div>{waterfall ? <Chart label="三要素变动瀑布图" option={waterfall}/> : <p className="empty">N/A · {comp?.reason ?? '没有完整可比上期，不能生成桥接'}</p>}<div className="table-scroll"><table><thead><tr><th>成本要素</th><th>单位成本（元/盒）</th><th>总额（元）</th><th>变动额（{isUnit ? '元/盒' : '元'}）</th><th>贡献度</th><th>去年同期（元/盒）</th><th>单位同比</th><th>单位环比</th><th>总额环比</th></tr></thead><tbody>{elements.map((e: any) => <tr key={e.key}><td>{e.name}</td><td>{fmt(e.unit)}</td><td>{fmt(e.total)}</td><td>{fmt(e.comparisons?.[comparisonKey]?.[basis]?.delta ?? (comparisonKey==='mom'?e.delta:null))}</td><td>{pct(e.comparisons?.[comparisonKey]?.[basis]?.contribution ?? (comparisonKey==='mom'?e.contribution:null))}</td><td>{fmt(e.comparisons?.yoy?.unit?.base ?? snapshot.period_values?.yoy?.elements_unit?.[e.key])}</td><td>{pct(e.comparisons?.yoy?.unit?.rate)}</td><td className={e.alerts?.unit ? 'increase' : ''}>{pct(e.unit_mom)} {e.alerts?.unit ? '重点分析' : ''}</td><td className={e.alerts?.total ? 'increase' : ''}>{pct(e.total_mom)} {e.alerts?.total ? '重点分析' : ''}</td></tr>)}</tbody></table></div><p className="muted">告警：三要素环比严格超过 ±10%。恰好 ±10% 不触发；负贡献及超过 100% 均保留。总额受单位成本和产量共同影响。</p></section>
 {snapshot.budget_bridge && <section className="panel"><h2>预算总额差异桥接</h2><DataTable rows={[{ '产量影响(元)': snapshot.budget_bridge.quantity_effect, '单位成本影响(元)': snapshot.budget_bridge.unit_cost_effect, '总额差异(元)': snapshot.budget_bridge.total_delta }]}/><p className="muted">{snapshot.budget_bridge.formula}。{snapshot.budget_bridge.note}。</p></section>}{snapshot.materials_summary?.length>0&&<section className="panel"><h2>原料变动贡献排序</h2><p className="muted">{snapshot.product} · {snapshot.factory} · {snapshot.period?.end}；按原料每盒成本变动对材料增量的贡献排序。采购价与实物耗量尚须另行核查。</p><DataTable rows={snapshot.materials_summary.map((r:any)=>({'原料':r.name,'上期（元/盒）':fmt(r.previous),'本期（元/盒）':fmt(r.current),'差额（元/盒）':fmt(r.delta),'占材料增量':pct(r.contribution)}))}/></section>}<NarrativePanel snapshot={snapshot} onEvidence={onEvidence}/><Details details={snapshot.details}/>
 <section className="panel"><h2>行业静态模拟参考</h2><p>{snapshot.industry?.notice}</p><p>规格换算后的单位成本：<strong>{fmt(snapshot.industry?.converted_unit_cost, 4)} {snapshot.industry?.unit}</strong>（每盒成本 ÷ {snapshot.industry?.divisor}）</p><DataTable rows={snapshot.industry?.rows ?? []}/></section>
 </>;
}
