import { useState, useEffect, useCallback, useRef } from 'react';
import { api, Selection, IndustryContext, contextQuery } from './api';
import { Catalog, Snapshot, BenchmarkData } from './types';
import { useJobsActions } from './hooks';
import Analysis from './Analysis';
import ProductMonthHeatmap from './ProductMonthHeatmap';
import Benchmark from './Benchmark';
import Tasks from './Tasks';
import Evidence, { EvidenceDrawer } from './Evidence';
import DecisionCard from './DecisionCard';
import DataCenter from './DataCenter';
import KnowledgeCenter from './KnowledgeCenter';
import ModelSettings from './ModelSettings';
const sections = ['分析工作台', '跨厂对标', '报告与整改', '数据中心', '知识中心', '系统设置'];
const initialSelection: Selection = {context_id:'',factory:'',product:'',month:'',analysis_type:'monthly',basis:'unit'};
export default function App() {
 const [tab,setTab]=useState(0),[contexts,setContexts]=useState<IndustryContext[]>([]),[contextId,setContextId]=useState(''),[catalog,setCatalog]=useState<Catalog|null>(null),[selection,setSelection]=useState(initialSelection),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[benchmark,setBenchmark]=useState<BenchmarkData|null>(null),[left,setLeft]=useState(''),[right,setRight]=useState(''),[error,setError]=useState(''),[analysisLoading,setAnalysisLoading]=useState(false),[benchmarkLoading,setBenchmarkLoading]=useState(false),[drawer,setDrawer]=useState<any>(null),[reload,setReload]=useState(0),[benchElapsed,setBenchElapsed]=useState(0);
 const activeContext=contexts.find(c=>c.context_id===contextId), currentContext=useRef(contextId);currentContext.current=contextId;
 const {jobs,setJobs,actions,setActions,refresh}=useJobsActions(tab,contextId);
 // reload 计数：任一数据请求失败后"重试"按钮递增，触发对应 effect 重取（#9 全站零重试修复）
 useEffect(()=>{const c=new AbortController();api('/industry/catalog',undefined,c.signal).then(x=>{if(c.signal.aborted)return;setContexts(x.contexts);const requested=new URLSearchParams(window.location.search).get('context_id');if(!contexts.length)setContextId(x.contexts.some((v:IndustryContext)=>v.context_id===requested)?requested:x.default_context_id??x.contexts[0]?.context_id??'');}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[reload]);
 useEffect(()=>{if(!contextId)return;const c=new AbortController();setCatalog(null);setSnapshot(null);setBenchmark(null);setJobs([]);setActions([]);setDrawer(null);setError('');api(`/catalog?${contextQuery(contextId)}`,undefined,c.signal).then(x=>{if(c.signal.aborted)return;setSelection({...initialSelection,context_id:contextId,factory:x.factories[0]??'',product:x.products[0]??'',month:x.months.at(-1)??''});setLeft(x.factories[0]??'');setRight(x.factories[1]??'');setCatalog(x)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[contextId,reload]);
 const {factory,product,month,analysis_type,basis}=selection;
 useEffect(()=>{if(!catalog||selection.context_id!==contextId)return;const c=new AbortController();setAnalysisLoading(true);setError('');setSnapshot(null);api('/analyses',selection,c.signal).then(x=>{if(!c.signal.aborted)setSnapshot(x)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setAnalysisLoading(false)});return()=>c.abort()},[catalog,contextId,selection,reload]);
 useEffect(()=>{if(tab!==1||!catalog||selection.context_id!==contextId||!left||!right||left===right)return;const c=new AbortController();setBenchmarkLoading(true);setError('');setBenchmark(null);setBenchElapsed(0);const params=new URLSearchParams({context_id:contextId,product,month,left,right,analysis_type,basis});api(`/benchmarks?${params}`,undefined,c.signal).then(x=>{if(!c.signal.aborted)setBenchmark(x)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBenchmarkLoading(false)});return()=>c.abort()},[tab,catalog,contextId,product,month,left,right,analysis_type,basis,reload]);
 // 对标耗时反馈（#8）：每秒更新已等待时间，用户不再面对无进度长等待
 useEffect(()=>{if(!benchmarkLoading)return;setBenchElapsed(0);const timer=setInterval(()=>setBenchElapsed(n=>n+1),1000);return()=>clearInterval(timer)},[benchmarkLoading]);
 const closeDrawer=useCallback(()=>setDrawer(null),[]);
 const changeIndustry=(id:string)=>{const next=contexts.find(c=>c.industry_id===id);if(next)setContextId(next.context_id)};
 const changeRange=(kind:Selection['analysis_type'])=>setSelection(s=>{const ends=catalog?.months.filter((m:string)=>['03','06','09','12'].includes(m.slice(-2)))??[];const quarterEnd=`${s.month.slice(0,4)}-${String(Math.ceil(Number(s.month.slice(-2))/3)*3).padStart(2,'0')}`;return {...s,analysis_type:kind,month:kind==='quarterly'?(ends.includes(quarterEnd)?quarterEnd:ends.at(-1)??s.month):s.month}});
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">衡</span><div><strong>药衡智析</strong><small>产品成本分析工作台</small></div></div><nav aria-label="主导航">{sections.map((s,i)=><button aria-current={tab===i?'page':undefined} className={tab===i?'active':''} key={s} onClick={()=>setTab(i)}><span className="nav-number">0{i+1}</span>{s}</button>)}</nav><div className="sidebar-footer"><strong>本地演示环境</strong><p>确定性计算 · 可追溯证据<br/>专业报告 · 模拟 RPA</p><span>企业赛题 · 创灵境</span></div></aside><div className="workspace"><header className="topbar"><span>产品成本智能分析报告系统</span><span className="local-dot">本地服务</span></header><main><div className="page-heading"><div><h1>{sections[tab]}</h1><p>{['从成本变化追踪数据，连接证据与可核查的行动建议。','同产品、同规格、同期间，逐层查看工厂差异。','固定输入版本，生成报告；确认后发送模拟通知。','上传业务数据、知识资料与模板：预览、映射、质检、发布一站式完成。','知识库状态、构建与证据检索：来源、位置与适用范围可核对。','模型连接与路由：API 与后台任务同一配置，测试为真实短生成。'][tab]}</p></div><span className="outline-label">{activeContext?.data_label??'正在读取数据范围'}</span></div>
 {tab<=2&&<section className="filters context-filters" aria-label="行业与企业"><label>行业包<select aria-label="行业包" value={activeContext?.industry_id??''} onChange={e=>changeIndustry(e.target.value)}>{[...new Map(contexts.map(c=>[c.industry_id,c])).values()].map(c=><option key={c.industry_id} value={c.industry_id}>{c.industry_name}</option>)}</select></label><label>企业<select aria-label="企业" value={contextId} onChange={e=>setContextId(e.target.value)}>{contexts.filter(c=>c.industry_id===activeContext?.industry_id).map(c=><option key={c.context_id} value={c.context_id}>{c.company_name}</option>)}</select></label><p className="muted">已建报告与任务保留创建时的企业、数据和政策版本。</p></section>}
 {tab<=2&&catalog&&<section className="filters" aria-label="分析筛选"><label>产品<select aria-label="产品" value={product} onChange={e=>setSelection(s=>({...s,product:e.target.value}))}>{catalog.products.map(p=><option key={p}>{p}</option>)}</select></label><label>工厂<select aria-label="工厂" value={factory} onChange={e=>setSelection(s=>({...s,factory:e.target.value}))}>{catalog.factories.map(f=><option key={f}>{f}</option>)}</select></label><label>{analysis_type==='quarterly'?'季度末月':'月份'}<select aria-label="月份" value={month} onChange={e=>setSelection(s=>({...s,month:e.target.value}))}>{catalog.months.filter((m:string)=>analysis_type!=='quarterly'||['03','06','09','12'].includes(m.slice(-2))).map((m:string)=><option key={m}>{m}</option>)}</select></label><label>报告范围<select aria-label="报告范围" value={analysis_type} onChange={e=>changeRange(e.target.value as Selection['analysis_type'])}><option value="monthly">月度分析</option><option value="quarterly" disabled={!catalog.months.some((m:string)=>['03','06','09','12'].includes(m.slice(-2)))}>季度分析</option><option value="special">专题分析</option></select></label><div className="basis"><span>成本口径</span><div role="group" aria-label="成本口径">{(['unit','total'] as const).map(b=><button key={b} aria-pressed={basis===b} className={basis===b?'selected':''} onClick={()=>setSelection(s=>({...s,basis:b}))}>{b==='unit'?'单位':'总额'}</button>)}</div></div></section>}
 {analysis_type==='quarterly'&&<p className="notice">季度单位成本 = 季度总成本 ÷ 季度可比产量。缺月不补零；趋势图保留月度口径。</p>}<Capabilities value={snapshot?.capabilities??catalog?.capabilities??activeContext?.capabilities}/>{error&&<ErrorBox message={error} onRetry={()=>{setError('');setReload(n=>n+1)}}/>}{(tab===1?benchmarkLoading:analysisLoading)&&<div className="loading" role="status">{tab===1?`正在对标分析：差异计算、证据检索与原因假设（约 10–60 秒），已等待 ${benchElapsed} 秒…`:'正在读取固定版本数据…'}</div>}
 {tab===0&&snapshot&&<><DecisionCard selection={selection} onApplied={refresh} onError={message=>{if(currentContext.current===contextId)setError(message)}}/><Analysis key={`${contextId}:${snapshot.snapshot_id}`} snapshot={snapshot} basis={basis} onEvidence={setDrawer}/></>}{tab===0&&catalog&&selection.context_id===contextId&&<ProductMonthHeatmap key={contextId} selection={selection} onSelect={(product,month)=>setSelection(s=>({...s,product,month,analysis_type:'monthly'}))}/>} {tab===1&&<><div className="comparison-filters"><label>分析工厂<select aria-label="分析工厂" value={left} onChange={e=>{setLeft(e.target.value);setBenchmark(null)}}>{catalog?.factories.map((f:string)=><option key={f} disabled={f===right}>{f}</option>)}</select></label><label>基准工厂<select aria-label="基准工厂" value={right} onChange={e=>{setRight(e.target.value);setBenchmark(null)}}>{catalog?.factories.map((f:string)=><option key={f} disabled={f===left}>{f}</option>)}</select></label></div>{!catalog||catalog.factories.length<2?<p className="notice">当前数据仅有一个工厂，跨厂对标不可用。</p>:<Benchmark data={benchmark} analysisType={analysis_type} onSwap={()=>{setLeft(right);setRight(left);setBenchmark(null)}} onEvidence={setDrawer}/>}</>}{tab===2&&<Tasks key={contextId} selection={selection} snapshot={snapshot} jobs={jobs} actions={actions} refresh={refresh} onError={message=>{if(currentContext.current===contextId)setError(message)}}/>}{tab===3&&<DataCenter/>}{tab===4&&<KnowledgeCenter contextId={contextId} product={product} month={month} factory={factory} onOpen={setDrawer}/>}{tab===5&&<ModelSettings/>}<footer>成本共变仅支持原因假设；生产变更与整改完成均须人工确认。合成样例仅验证框架，不代表行业基准。</footer></main></div>{drawer&&<EvidenceDrawer value={drawer} onClose={closeDrawer}/>}</div>
}
function ErrorBox({message,onRetry}:{message:string;onRetry:()=>void}){return <div className="error" role="alert">请求失败：{message}<button className="retry" onClick={onRetry}>重试</button></div>}
const capabilityText=(value:string)=>String(value).replaceAll('pdf_service','PDF 转换服务').replaceAll('model_service','应用模型服务').replaceAll('rpa_service','模拟任务服务');
function Capabilities({value}:{value:any}){if(!value)return null;const rows=Array.isArray(value)?value:Object.entries(value).map(([key,v])=>typeof v==='object'&&v!==null?{key,...v}:{key,status:v===true?'AVAILABLE':'UNAVAILABLE'});return <details className="capabilities"><summary>当前分析能力与数据缺口</summary><ul>{rows.map((v:any,i:number)=><li key={v.key??v.id??i}><strong>{v.label??v.name??v.key??v.id}</strong>：{({AVAILABLE:'可用',PASS:'可用',DEGRADED:'降级',BLOCKED:'不可用',UNAVAILABLE:'不可用',MISSING_DATA:'缺少数据'} as Record<string,string>)[String(v.status).toUpperCase()]??v.status??'待核验'}{v.reason?`；${capabilityText(v.reason)}`:''}{(v.missing_fields??v.missing)?.length?`；需补充 ${(v.missing_fields??v.missing).map(capabilityText).join('、')}`:''}</li>)}</ul></details>}
