import {useEffect,useState} from 'react';
import {api} from './api';
import {AnalysisStatus,DeveloperDetails,cleanText} from './presentation';
export const findingLabel=(kind:string)=>({numeric_fact:'数值事实',document_fact:'文档事实',hypothesis:'待核查假设',insufficient_evidence:'证据不足',recommendation:'改进建议'}[kind]??kind);
export function snapshotReport(jobs:any[],snapshotId?:string){return jobs.find(j=>j.result?.snapshot?.snapshot_id===snapshotId&&['SUCCEEDED','DEGRADED'].includes(j.status)&&j.result?.narrative);}
export default function NarrativePanel({snapshot,onEvidence}:{snapshot:any;onEvidence:(value:any)=>void}){
 const [submitting,setSubmitting]=useState(false);
 const [report,setReport]=useState<any>(null),[pending,setPending]=useState<string|null>(null),[stage,setStage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setReport(null);setPending(null);setError('');api('/jobs',undefined,c.signal).then(response=>{const jobs=Array.isArray(response)?response:response.jobs??[];setReport(snapshotReport(jobs,snapshot.snapshot_id));const active=jobs.find((j:any)=>(j.input?.snapshot_id===snapshot.snapshot_id||j.result?.snapshot?.snapshot_id===snapshot.snapshot_id)&&!['SUCCEEDED','DEGRADED','FAILED'].includes(j.status));if(active)setPending(active.id);}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort();},[snapshot.snapshot_id]);
 useEffect(()=>{if(!pending)return;const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const job=await api(`/jobs/${encodeURIComponent(pending)}`,undefined,c.signal);if(c.signal.aborted)return;setStage(job.stage);if(['SUCCEEDED','DEGRADED'].includes(job.status)){setReport(job);setPending(null);return;}if(job.status==='FAILED'){setError(job.error??'报告生成失败');setPending(null);return;}timer=setTimeout(poll,2000);}catch(e){if(!c.signal.aborted){setError(e instanceof Error?e.message:String(e));setPending(null);}}};void poll();return()=>{c.abort();clearTimeout(timer)};},[pending]);
 async function generate(){setSubmitting(true);setError('');setStage('提交中');try{const result=await api('/reports',{factory:snapshot.factory,product:snapshot.product,month:snapshot.month,analysis_type:snapshot.analysis_type,basis:snapshot.basis});setPending(result.job_id);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSubmitting(false)}}
 const narrative=report?.result?.narrative,evidence=report?.result?.evidence?.evidence??[];
 return <section className="panel narrative-panel"><div className="panel-heading"><h2>成本解释与建议</h2>{!narrative&&<button className="primary" disabled={Boolean(pending)||submitting} onClick={generate}>{pending||submitting?'生成中…':'生成分析报告'}</button>}</div>{!narrative&&<p className="muted">生成分析报告后展示与当前快照一致的解释和建议。数字由程序绑定，原因假设必须具备证据与缺证项。</p>}{pending&&<p role="status">报告阶段：{stage} · 可在“报告与任务”查看并下载。</p>}{error&&<p className="error" role="alert">{error}</p>}{narrative&&<><AnalysisStatus narrative={narrative}/>{narrative.findings?.map((f:any,i:number)=><article className="finding" key={i}><strong>{findingLabel(f.claim_type)}</strong><p>{cleanText(f.rendered_text??f.text_template)}</p>{f.missing_evidence?.length>0&&<p className="muted">缺少证据：{f.missing_evidence.join('；')}</p>}{f.suggestion&&<p>建议：{f.suggestion}</p>}<button onClick={()=>onEvidence({...f,evidence:evidence.filter((e:any)=>f.evidence_refs?.includes(e.evidence_id)),snapshot_id:snapshot.snapshot_id})}>查看计算与证据依据</button></article>)}<DeveloperDetails value={{narrative,evidence,report_status:report.status}}/></>}</section>;
}
