// API 契约类型（2026-09-21 修复 #10）：以 backend/pharma 的 Pydantic 模型与
// 实测响应为依据手工对齐；后端字段变化时此处同步。未覆盖的深层结构暂以
// any/unknown 显式标注（比散落的隐式 any 可审计），后续逐步收紧。
export type Metric = { metric_id: string; label?: string; value: string | number | null; display?: string; display_value?: string; unit: string; reason?: string | null; comparison_period?: string[]; formula?: string; numerator?: string | number | null; denominator?: string | number | null; row_keys?: string[] };
export type Artifact = { artifact_id: string; status: string; sha256?: string };
export type Narrative = { status: 'PASS' | 'DEGRADED'; model?: string; model_live?: boolean; model_responded?: boolean; failure_reasons?: string[]; findings: any[] };
export type JobResult = { snapshot?: any; narrative?: Narrative; docx?: Artifact; pdf?: Artifact; audit?: Artifact; acceptance?: any; execution_status?: string; generation_mode?: string };
export type Job = { id: string; kind: string; status: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'DEGRADED' | 'FAILED'; stage?: string; input: any; result: JobResult | null; created: string; updated: string; error?: string | null; cache_key?: string | null };
export type RpaAction = { id: string; payload: any; payload_hash: string; status: string; metadata: any; remote?: any; delivery?: { http_accepted?: boolean; notification?: string; remediation?: string }; responsibility_confirmation?: { status?: string; confirmed_by?: string; confirmed_at?: string }; error?: string };
export type Catalog = { factories: string[]; products: string[]; months: string[]; snapshot_id: string; context_id: string; quantity_unit: string; currency: string; demo_assignee?: string; capabilities?: unknown };
export type Snapshot = { snapshot_id: string; context_id: string; factory: string; product: string; month: string; period: { start: string; end: string }; analysis_type: string; basis: string; specification?: string; quantity_unit?: string; currency?: string; metrics: Record<string, Metric>; elements: any[]; trend: { month: string; unit_cost: string | null; total_cost: string | null; quantity: string | null }[]; focus?: any; details?: any; materials_summary?: any[]; budget_bridge?: any; industry?: any; capabilities?: any; period_values?: any; period_changes?: any; specialized_metrics?: any };
export type BenchmarkData = { analysis_type: string; period: any; direction: string; product: string; month: string; left: string; right: string; summary: any[]; elements: any[]; details: { left: any; right: any }; hypotheses: any[]; narrative?: Narrative; evidence?: any; limits?: any };
