import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
process.env.TMPDIR='/tmp';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=path.join(root,'06_评测');await mkdir(out,{recursive:true});
const base=process.env.PHARMA_E2E_URL??'http://127.0.0.1:8765';
const executablePath=process.env.PHARMA_CHROME_PATH??'/mnt/d/AI_Cache/ms-playwright/chromium-1228/chrome-linux64/chrome';
const report={started_at:new Date().toISOString(),url:base,browser_plugin:'ABSENT: Browser plugin not available; regular Playwright selected',browser:'Chrome for Testing',executablePath,viewports:[],checks:[],console_errors:[],network_errors:[],status:'RUNNING'};
let browser,context,page;const check=(name,pass,details='')=>{report.checks.push({name,status:pass?'PASS':'FAIL',details});if(!pass)throw Error(name+': '+details)};
const step=async(name,fn)=>{await fn();console.log('PASS '+name)};
try{
 browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});report.browser_version=browser.version();
 context=await browser.newContext({viewport:{width:1366,height:768},locale:'zh-CN'});await context.tracing.start({screenshots:true,snapshots:true,sources:false});page=await context.newPage();
 page.on('pageerror',e=>report.console_errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.console_errors.push(m.text()+' @ '+m.location().url)});page.on('requestfailed',r=>{if(!r.failure()?.errorText.includes('ERR_ABORTED'))report.network_errors.push({url:r.url(),error:r.failure()?.errorText})});
 await step('首屏与独立S1 golden',async()=>{await page.goto(base,{waitUntil:'networkidle'});await page.getByRole('button',{name:'单位成本'}).first().waitFor({timeout:30000}).catch(()=>{});check('page_identity',(await page.title()).includes('药衡智析'));await page.getByLabel('产品',{exact:true}).selectOption('银黄口服液');await page.getByLabel('工厂',{exact:true}).selectOption('中药一厂');await page.getByLabel('月份',{exact:true}).selectOption('2026-05');await page.getByText('11.21',{exact:false}).first().waitFor({timeout:30000});const body=await page.locator('body').innerText();check('S1_unit_cost',body.includes('11.21'));check('S1_mom',body.includes('+2.84%'));check('S1_yoy',body.includes('+4.67%'));check('S1_budget',body.includes('+5.75%'));check('not_blank',body.includes('三要素成本结构'));check('no_framework_overlay',await page.locator('vite-error-overlay').count()===0);check('1366_no_horizontal_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.viewports.push({width:1366,height:768,status:'PASS'});await page.screenshot({path:path.join(out,'browser_1366_cost.png'),fullPage:false});});
 await step('指标来源抽屉',async()=>{await page.locator('.metric').first().click();await page.getByRole('dialog',{name:'证据与计算口径'}).waitFor();check('metric_source_drawer',(await page.getByRole('dialog').innerText()).includes('source_hash'));await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await step('单位/总额及趋势截止',async()=>{await page.getByRole('button',{name:'总额',exact:true}).click();await page.locator('.metric').first().getByText('总成本',{exact:true}).waitFor();await page.getByText('查看精确趋势数据').click();const rows=await page.locator('details[open] tbody tr').allTextContents();check('trend_no_future',rows.every(r=>!r.includes('2026-06')));await page.getByRole('button',{name:'单位',exact:true}).click();});
 await step('三步对标与双方向分母',async()=>{await page.getByLabel('产品',{exact:true}).selectOption('板蓝根颗粒');await page.getByRole('button',{name:/跨厂对标/}).click();await page.getByText('+6.69%',{exact:true}).first().waitFor({timeout:30000});check('S2_forward',(await page.locator('main').innerText()).includes('7.97'));check('S2_missing_details',(await page.locator('main').innerText()).includes('不按比例推算'));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'browser_benchmark.png'),fullPage:true});await page.getByRole('button',{name:'交换工厂方向'}).click();await page.getByText('−6.27%',{exact:true}).or(page.getByText('-6.27%',{exact:true})).first().waitFor({timeout:30000});check('S2_reverse',true);});
 await step('真实知识证据检索',async()=>{await page.getByRole('button',{name:/数据与证据/}).click();await page.getByLabel('知识检索问题').fill('设备停机 维修');await page.getByRole('button',{name:'检索证据',exact:true}).click();await page.locator('.evidence-result').first().waitFor({timeout:120000});check('kb_result_has_text',(await page.locator('.evidence-result').first().innerText()).length>40);await page.locator('.evidence-result').first().getByRole('button').click();check('kb_source_drawer',(await page.getByRole('dialog').innerText()).includes('evidence_id'));await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await step('S3报告与明确确认发送',async()=>{await page.getByLabel('产品',{exact:true}).selectOption('六味地黄胶囊');await page.getByLabel('月份',{exact:true}).selectOption('2026-03');await page.getByRole('button',{name:/报告与任务/}).click();await page.getByRole('button',{name:'生成报告',exact:true}).waitFor();const jobResponse=page.waitForResponse(r=>r.url().endsWith('/api/reports')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成报告',exact:true}).click();const requestedJob=await (await jobResponse).json();const reportRow=page.locator('.job').filter({hasText:requestedJob.job_id.slice(0,16)});await page.getByText('报告任务已提交：',{exact:false}).waitFor();check('report_job_submitted',true);await page.getByLabel('演示责任人').fill('演示责任人');await page.getByLabel('部门',{exact:true}).fill('演示生产管理部');await page.getByLabel('业务发现').fill('2026年3月六味地黄胶囊单位成本下降、总额上升；对照停机记录核查维护计划执行情况，设备事件仅支持待核查假设，不证明净因果。');await page.getByLabel('建议内容').fill('核查设备PDF第4页停机与维护记录，评估预防性维护计划。生产或GMP变更需人工批准。');const draftResponse=page.waitForResponse(r=>r.url().endsWith('/api/actions')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成任务草稿'}).click();const draft=await (await draftResponse).json();const taskRow=page.locator('.task').filter({hasText:draft.id});await taskRow.waitFor();if(draft.status==='DRAFT'){await taskRow.getByRole('button',{name:'确认并发送模拟通知'}).waitFor({timeout:30000});check('rpa_draft_requires_confirmation',true);await taskRow.getByRole('button',{name:'确认并发送模拟通知'}).click();}else{check('rpa_reused_confirmed_payload',draft.status==='SENT',draft.status);}await taskRow.getByText('原版 mock 已确认模拟发送。',{exact:true}).waitFor({timeout:60000});check('rpa_provided_mock_sent',true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'browser_tasks.png'),fullPage:true});await reportRow.getByRole('link',{name:/Word 下载/}).waitFor({timeout:300000});check('report_docx_link',true);await reportRow.getByRole('link',{name:/PDF 下载/}).waitFor({timeout:120000});check('report_pdf_link',true);for(const [kind,magic] of [['Word','PK'],['PDF','%PDF']]){const [download]=await Promise.all([page.waitForEvent('download'),reportRow.getByRole('link',{name:new RegExp(kind+' 下载')}).click()]);const bytes=await readFile(await download.path());check('download_'+kind,bytes.length>4000&&bytes.subarray(0,magic.length).toString()===magic,`${bytes.length} bytes`);}});
 await step('1920桌面布局',async()=>{await page.setViewportSize({width:1920,height:1080});await page.getByLabel('产品',{exact:true}).selectOption('银黄口服液');await page.getByLabel('月份',{exact:true}).selectOption('2026-05');await page.getByRole('button',{name:/成本分析/}).click();await page.getByText('11.21',{exact:false}).first().waitFor();check('1920_no_horizontal_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.viewports.push({width:1920,height:1080,status:'PASS'});await page.screenshot({path:path.join(out,'browser_1920_cost.png'),fullPage:false});});
 check('console_health',report.console_errors.length===0,report.console_errors.join('\n'));check('network_health',report.network_errors.length===0,JSON.stringify(report.network_errors));report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);console.error(String(e));if(page)await page.screenshot({path:path.join(out,'browser_failure.png'),fullPage:false}).catch(()=>{});}finally{report.finished_at=new Date().toISOString();if(context)await context.tracing.stop({path:path.join(out,'browser_trace.zip')}).catch(()=>{});if(browser)await browser.close();await writeFile(path.join(out,'browser_results.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'browser_run_history.jsonl'),JSON.stringify({started_at:report.started_at,status:report.status,error:report.error,checks:report.checks})+'\n',{flag:'a'});console.log(JSON.stringify({status:report.status,checks:report.checks.length,report:path.join(out,'browser_results.json')}));if(report.status!=='PASS')process.exitCode=1;}
