import {spawn} from 'node:child_process';
import {readFile,writeFile,copyFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'06_评测');
const results={created_at:new Date().toISOString(),url:'http://localhost:8765',viewport:{width:1366,height:768},scope:'Windows browsers headless real DOM and screenshot smoke; full interactions separately tested with Linux Chrome for Testing',browsers:[]};
for(const [name,exe] of [['Edge','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'],['Chrome','C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe']]){
 if(process.env.PHARMA_WINDOWS_BROWSER&&process.env.PHARMA_WINDOWS_BROWSER!==name)continue;
 const key='yaoheng-'+name.toLowerCase()+'-qa';const win='D:\\AI_Temp\\tmp\\'+key,linux='/mnt/d/AI_Temp/tmp/'+key;
 const command=`$ErrorActionPreference='Stop'; $exe='${exe}'; $args=@('--headless','--disable-gpu','--no-first-run','--no-default-browser-check','--user-data-dir=${win}-profile','--window-size=1366,768','--virtual-time-budget=15000','--screenshot=${win}.png','--dump-dom','http://localhost:8765'); $p=Start-Process -FilePath $exe -ArgumentList $args -PassThru -RedirectStandardOutput '${win}.html' -RedirectStandardError '${win}.stderr'; if(-not $p.WaitForExit(45000)){Stop-Process -Id $p.Id -Force; throw 'Project browser process timeout'}; [pscustomobject]@{version=(Get-Item $exe).VersionInfo.ProductVersion;exit_code=$p.ExitCode}|ConvertTo-Json -Compress`;
 const result={name,executable:exe,status:'NOT_RUN'};try{const proc=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',command]);let stdout='',stderr='';proc.stdout.on('data',b=>stdout+=b);proc.stderr.on('data',b=>stderr+=b);const code=await new Promise((resolve,reject)=>{proc.on('error',reject);proc.on('exit',resolve)});result.command_exit=code;if(code!==0)throw Error(stderr.slice(-1500));try{Object.assign(result,JSON.parse(stdout.trim()))}catch{result.launch_output=stdout.slice(-300)}const dom=await readFile(linux+'.html','utf8');result.page_identity=dom.includes('药衡智析');result.app_content=dom.includes('成本变动桥接')&&dom.includes('11.21');result.no_overlay=!dom.includes('<vite-error-overlay');await copyFile(linux+'.png',path.join(out,'browser_windows_'+name.toLowerCase()+'.png'));result.screenshot='browser_windows_'+name.toLowerCase()+'.png';result.status=result.page_identity&&result.app_content&&result.no_overlay?'PASS':'FAIL';}catch(e){result.status='BLOCKED';result.error=String(e)}results.browsers.push(result);console.log(JSON.stringify(result));}
await writeFile(path.join(out,'browser_windows_history.jsonl'),JSON.stringify(results)+'\n',{flag:'a'});let previous;try{previous=JSON.parse(await readFile(path.join(out,'browser_windows_results.json'),'utf8'))}catch{}if(previous&&process.env.PHARMA_WINDOWS_BROWSER)results.browsers=[...previous.browsers.filter(b=>b.name!==process.env.PHARMA_WINDOWS_BROWSER),...results.browsers];await writeFile(path.join(out,'browser_windows_results.json'),JSON.stringify(results,null,2));if(results.browsers.some(b=>b.status!=='PASS'))process.exitCode=1;
