import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
process.env.TMPDIR='/tmp';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'06_评测/incremental_20260916/plan_browser');await fs.mkdir(out,{recursive:true});
const html=await fs.readFile(path.join(root,'07_交付/药析证链_制药成本智能分析一等奖方案.html'));const artifact=JSON.parse(await fs.readFile(path.join(root,'07_交付/artifact.json'),'utf8'));
const result={started_at:new Date().toISOString(),status:'RUNNING',scope:'现有方案HTML浏览器渲染及数据口径，非报告合格判定',checks:[],console_errors:[],screenshots:[],findings:[]};
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});let browser;const check=(name,ok,detail='')=>{result.checks.push({name,status:ok?'PASS':'FAIL',detail});if(!ok)result.status='FAIL'};
try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.PHARMA_CHROME_PATH??'/mnt/d/AI_Cache/ms-playwright/chromium-1228/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1366,height:768}});page.on('pageerror',e=>result.console_errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.documentElement.dataset.dataAnalyticsPortableReader==='ready',{timeout:30000});
const body=await page.locator('body').innerText();await fs.writeFile(path.join(out,'visible_text.txt'),body);check('page_identity',(await page.title()).includes('药析证链'));check('not_blank',body.includes('药衡智析'));check('explicit_partial',body.includes('FINAL_STATUS=PARTIAL')&&body.includes('PENDING_HUMAN_AND_GLM'));check('glm_credentials_blocked',body.includes('glm-5.3-flash')&&body.includes('BLOCKED')&&body.includes('凭据缺失'));check('no_overall_pass_claim',!body.includes('FINAL_STATUS=PASS')&&!body.includes('COMPETITION_READY=PASS'));const runtime=await page.evaluate(()=>window.__DATA_ANALYTICS_PORTABLE_ARTIFACT__);check('runtime_matches_artifact',JSON.stringify(runtime)===JSON.stringify(artifact));
check('comparison_values_visible',['78.26','89.19','78.72'].every(v=>body.includes(v)));
const comparison=runtime.snapshot.datasets.scenario_comparison.filter(r=>r.产品==='板蓝根颗粒');for(const [basis,value] of [['环比',78.26],['同比',89.19],['预算差异',78.72]]){const r=comparison.find(r=>r.比较基准===basis);check('banlangen_'+basis,Math.abs(r.主要贡献率-value)<0.005,JSON.stringify(r));}
for(const id of ['R26','R27','R28']){const r=runtime.snapshot.datasets.requirements.find(r=>r.ID===id);check(id+'_partial',r.当前状态==='部分满足',r.当前证据与缺口)}
for(const v of [{width:1366,height:768},{width:1920,height:1080}]){await page.setViewportSize(v);await page.evaluate(()=>window.scrollTo(0,0));check(v.width+'_no_page_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));let f=path.join(out,`${v.width}_overview.png`);await page.screenshot({path:f,fullPage:false});result.screenshots.push(f);for(const [label,title] of [['comparison','三个场景的单位成本比较'],['contribution','三场景材料贡献与比较口径'],['requirements','赛题逐条合规追踪矩阵'],['model','GLM-5.3-Flash应用网关']]){const el=page.locator('#data-analytics-portable-reader').getByText(title,{exact:true}).first();if(await el.count()){await el.scrollIntoViewIfNeeded();f=path.join(out,`${v.width}_${label}.png`);await page.screenshot({path:f,fullPage:false});result.screenshots.push(f)}}}
result.table_controls=await page.locator('button').evaluateAll(es=>es.map(e=>({text:e.textContent,aria:e.getAttribute('aria-label'),title:e.getAttribute('title')})));const next=page.getByRole('button',{name:/next/i}).first();if(await next.count())await next.click();const r26=page.locator('#data-analytics-portable-reader').getByText('R26',{exact:true}).first();check('r26_rendered_in_table',await r26.count()>0);if(await r26.count()){await r26.scrollIntoViewIfNeeded();const file=path.join(out,'1920_r26_r28.png');await page.screenshot({path:file,fullPage:false});result.screenshots.push(file)}
check('charts_rendered',await page.locator('svg,canvas').count()>0);check('console_health',result.console_errors.length===0);
const stale=[['verdict','四份报告按实际任务终态验收'],['roadmap','参赛包装和发布由后续授权处理'],['questions','最终修复通过'],['scope','实施审计日期2026-09-15']];for(const[id,text]of stale){const b=artifact.manifest.blocks.find(b=>b.id===id);if(b?.body?.includes(text))result.findings.push({block:id,text,severity:id==='verdict'?'content_contract':'stale_wording'})}
if(!artifact.manifest.tables.some(t=>t.dataset==='scenario_comparison'))result.findings.push({block:'scenario_comparison',text:'比较贡献率存于chart tooltip数据，缺少默认可见比较明细表',severity:'presentation_limit'});
result.status=result.checks.every(c=>c.status==='PASS')?(result.findings.length?'PASS_WITH_FINDINGS':'PASS'):'FAIL';
}catch(e){result.status='FAIL';result.error=String(e)}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));result.finished_at=new Date().toISOString();await fs.writeFile(path.join(out,'results.json'),JSON.stringify(result,null,2));await fs.appendFile(path.join(out,'history.jsonl'),JSON.stringify(result)+'\n');console.log(JSON.stringify(result));if(result.status==='FAIL')process.exitCode=1}
