import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
process.env.TMPDIR='/tmp';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=path.join(root,'06_评测/incremental_20260916/browser');await mkdir(out,{recursive:true});
const base=process.env.PHARMA_E2E_URL??'http://127.0.0.1:8765';
const report={started_at:new Date().toISOString(),url:base,browser_plugin:'ABSENT: Browser plugin not available; existing Playwright reused',status:'RUNNING',viewports:[],checks:[],console_errors:[],artifacts:[],limitations:['真实人工归因0–5分、可读性和版式评审待评。','发送由用户确认；本浏览器流程只创建草稿，不代替用户确认。RPA发送与重启边界见后端回归。']};
let browser,page;
const check=(name,ok,details='')=>{report.checks.push({name,status:ok?'PASS':'FAIL',details});if(!ok)throw Error(`${name}: ${details}`)};
const runId=report.started_at.replace(/[:.]/g,'-');
const screenshot=async(name,fullPage=false)=>{const file=path.join(out,runId+'_'+name+'.png');await page.screenshot({path:file,fullPage});report.artifacts.push(file)};
const visibleText=()=>page.locator('body').innerText();
async function select(product,month,kind='monthly'){await page.getByLabel('报告范围',{exact:true}).selectOption(kind);await page.getByLabel('产品',{exact:true}).selectOption(product);await page.getByLabel('月份',{exact:true}).selectOption(month);await page.getByRole('button',{name:/成本分析/}).click();await page.locator('.metric').first().waitFor();await page.waitForFunction(()=>!document.querySelector('.loading'));}
try{
 await mkdir('/tmp/pharma-browser-downloads',{recursive:true});browser=await chromium.launch({downloadsPath:'/tmp/pharma-browser-downloads',executablePath:process.env.PHARMA_CHROME_PATH??[chromium.executablePath(),'/mnt/d/AI_Cache/ms-playwright/chromium-1228/chrome-linux64/chrome'].find(existsSync),headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1366,height:768},locale:'zh-CN',acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true,sources:false});page=await context.newPage();page.on('download',async d=>console.log('DOWNLOAD_STATUS',d.url(),await d.failure()));page.on('pageerror',e=>report.console_errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('net::ERR_FAILED'))report.console_errors.push(m.text())});

 await page.goto(base,{waitUntil:'networkidle'});await page.locator('.metric').first().waitFor({timeout:30000});
 check('page_identity',(await page.title()).includes('药衡智析')&&page.url().startsWith(base));check('not_blank',(await visibleText()).includes('成本趋势'));check('no_framework_overlay',await page.locator('vite-error-overlay').count()===0);
 await select('板蓝根颗粒','2026-05');await page.getByText('7.47',{exact:false}).first().waitFor();
 check('S2_unit_cost',(await page.locator('.metric').first().innerText()).includes('7.47'));
 check('review_default_no_internal_objects',!/(metric_refs|source_hash|generation_mode|free business number forbidden)/.test(await visibleText()));
 check('three_cost_charts_rendered',await page.locator('.chart canvas').count()===3);
 const trendPanel=page.locator('.panel').filter({has:page.getByLabel('成本趋势图')});check('no_future_trend',(await trendPanel.innerText()).includes('可用 5 个月')&&!(await trendPanel.innerText()).includes('2026-06'));
 for(const [comparison,expected] of [['mom','78.26%'],['yoy','89.19%'],['budget','78.72%']]){await page.getByLabel('桥接比较口径').selectOption(comparison);check(`material_contribution_${comparison}`,(await visibleText()).includes(expected));}
 const tableText=await page.locator('.panel').filter({has:page.getByLabel('桥接比较口径')}).innerText();check('yoy_elements_exact',['4.42','1.04','1.64'].every(x=>tableText.includes(x)));
 check('material_driver_83_33',(await visibleText()).includes('83.33%'));
 await page.getByLabel('桥接比较口径').selectOption('mom');await page.locator('.metric').first().click();check('metric_drawer_readable_sources',(await page.getByRole('dialog').innerText()).includes('数据来源：'));check('drawer_default_no_hash',!/(source_hash|metric_refs)/.test(await page.getByRole('dialog').innerText()));await page.getByRole('dialog').getByText('开发者详情（机器审计）').click();check('developer_audit_retained',(await page.getByRole('dialog').innerText()).includes('source_hash'));await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.evaluate(()=>window.scrollTo(0,0));check('1366_no_horizontal_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.viewports.push({width:1366,height:768});await screenshot('1366_cost');const chart=page.getByLabel('成本趋势图');await chart.hover({position:{x:220,y:110}});await page.waitForTimeout(250);check('echarts_trend_tooltip_interactive',/2026-0[1-5]/.test(await chart.innerText()));await screenshot('1366_chart_tooltip');
 await page.getByText('查看精确趋势数据').click();check('trend_precise_february',(await visibleText()).includes('7.25'));await page.getByRole('button',{name:'总额',exact:true}).click();await page.getByText('总成本',{exact:true}).first().waitFor();check('total_basis_changes_metric',(await page.locator('.metric').first().innerText()).includes('761,940'));await page.getByRole('button',{name:'单位',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.loading'));
 await page.getByRole('button',{name:/跨厂对标/}).click();await page.getByText('+6.69%',{exact:true}).first().waitFor({timeout:120000});const benchmarkText=await visibleText();check('benchmark_structure_exact',['40.00%','26.00%','34.00%'].every(x=>benchmarkText.includes(x)));check('benchmark_chart',await page.getByLabel('跨厂三要素对比图').locator('canvas').count()===1);await screenshot('1366_benchmark',true);await page.getByRole('button',{name:'交换工厂方向'}).click();await page.getByText('-6.27%',{exact:true}).first().waitFor({timeout:120000});check('benchmark_reverse_direction',true);
 await page.getByRole('button',{name:/数据与证据/}).click();await page.getByLabel('知识检索问题').fill('板蓝根颗粒 工艺 水提');await page.getByRole('button',{name:'检索证据',exact:true}).click();await page.getByText(/找到 \d+ 条候选依据/).waitFor({timeout:120000});const evidenceText=await visibleText();check('evidence_default_no_slice',!/(metric_refs|original_text|evidence_id|source_hash)/.test(evidenceText));const renderedHits=await page.locator('.evidence-result').allTextContents();check('evidence_no_other_product',renderedHits.every(t=>!t.includes('银黄口服液')&&!t.includes('六味地黄胶囊')));check('banlangen_process_real_page_three',renderedHits.some(t=>t.includes('生产工艺文档')&&/第\s*3\s*页/.test(t)));await screenshot('1366_evidence',true);
 await select('银黄口服液','2026-05');check('S1_unit_cost',(await page.locator('.metric').first().innerText()).includes('11.21'));
 await select('六味地黄胶囊','2026-03');check('S3_unit_cost',(await page.locator('.metric').first().innerText()).includes('17.02'));
 await select('银黄口服液','2026-06','quarterly');check('quarter_weighted_notice',(await visibleText()).includes('产量加权'));await screenshot('1366_quarter');
 await select('板蓝根颗粒','2026-05');await page.getByRole('button',{name:/报告与任务/}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/reports')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成报告',exact:true}).click();const generated=await (await response).json();report.generated_job=generated.job_id;const job=page.locator('.job').filter({hasText:generated.job_id.slice(0,16)});await job.getByRole('link',{name:/Word 下载/}).waitFor({timeout:300000});check('report_not_file_pass_equals_report_pass',(await job.innerText()).includes('尚未合格／待评')&&!(await job.innerText()).includes('下载 · PASS'));const jobText=await job.innerText();check('eight_acceptance_dimensions_exact',['文件可打开','计算一致','章节实质完整','证据适用','内容可读','视觉合格','任务可执行','模型实际参与'].every(x=>jobText.includes(x)));
 for(const [kind,magic] of [['Word','PK'],['PDF','%PDF']]){const [download]=await Promise.all([page.waitForEvent('download'),job.getByRole('link',{name:new RegExp(kind+' 下载')}).click()]);const data=await readFile(await download.path());check(`real_${kind}_download`,data.length>4000&&data.subarray(0,magic.length).toString()===magic);await download.saveAs(path.join(out,`downloaded_${kind==='Word'?'report.docx':'report.pdf'}`));}
 const [auditDownload]=await Promise.all([page.waitForEvent('download'),job.getByRole('link',{name:'机器审计附件'}).click()]);const audit=JSON.parse(await readFile(await auditDownload.path(),'utf8'));check('real_machine_audit_download',typeof audit==='object'&&Object.keys(audit).length>0);await auditDownload.saveAs(path.join(out,'downloaded_machine_audit.json'));
 await page.getByLabel('载入当前报告建议').locator('option').nth(1).waitFor({state:'attached'});await page.getByLabel('载入当前报告建议').selectOption('0');check('action_has_suggestion',(await page.getByLabel('建议内容').inputValue()).trim().length>5);check('action_expected_evidence',(await page.getByLabel('预期证据').inputValue()).trim().length>5);check('action_deadline_basis',(await page.getByLabel('期限依据').inputValue()).trim().length>5);check('unknown_assignee_not_invented',(await page.getByLabel('责任人',{exact:true}).inputValue())==='待分配');
 const draftResponse=page.waitForResponse(r=>r.url().endsWith('/api/actions')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成任务草稿',exact:true}).click();const draft=await(await draftResponse).json();report.draft_id=draft.id;check('draft_no_notification_before_confirmation',draft.status==='DRAFT');const task=page.locator(`[data-task-id="${draft.id}"]`);await task.waitFor();await page.getByRole('button',{name:'生成任务草稿',exact:true}).waitFor();const repeatResponse=page.waitForResponse(r=>r.url().endsWith('/api/actions')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成任务草稿',exact:true}).click();const repeated=await(await repeatResponse).json();check('duplicate_draft_reuses_task',repeated.id===draft.id&&repeated.status==='DRAFT');await task.getByRole('button',{name:'编辑草稿'}).click();await page.getByLabel('预期证据').fill((await page.getByLabel('预期证据').inputValue())+'；核对资料期间与版本（浏览器回归 '+runId+'）');const editResponse=page.waitForResponse(r=>r.url().endsWith('/api/actions/'+draft.id)&&r.request().method()==='PUT');await page.getByRole('button',{name:'保存草稿修改'}).click();const edited=await(await editResponse).json();check('edit_saves_action_details',edited.metadata?.expected_evidence?.some(x=>x.includes('核对资料期间与版本')));check('edit_changes_confirmation_identity',edited.payload_hash!==draft.payload_hash&&edited.status==='DRAFT');await task.getByText('核对资料期间与版本',{exact:false}).first().waitFor();await task.scrollIntoViewIfNeeded();await screenshot('1366_action_draft');
 await page.getByRole('checkbox',{name:'查看历史报告及失败记录'}).check();check('history_available',(await page.locator('.job').count())>=1);await page.getByRole('checkbox',{name:'查看历史报告及失败记录'}).uncheck();await page.evaluate(()=>window.scrollTo(0,0));await screenshot('1366_acceptance');
 for(const viewport of [{width:1920,height:1080},{width:390,height:844}]){await page.setViewportSize(viewport);await select('板蓝根颗粒','2026-05');check(`${viewport.width}_no_horizontal_overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.viewports.push(viewport);await screenshot(`${viewport.width}_cost`);}
 const selected=await(await page.request.post(base+'/api/analyses',{data:{product:'板蓝根颗粒',factory:'中药一厂',month:'2026-05',analysis_type:'monthly',basis:'unit'}})).json();await page.route('**/api/actions',async route=>{if(route.request().method()!=='GET')return route.continue();return route.fulfill({json:[{id:'ui-fixture-accepted',status:'ACCEPTED',metadata:{snapshot_id:selected.snapshot_id},payload:{task_title:'UI状态隔离验证（注入样例）',assignee:{name:'待分配',department:'待分配'}},remote:{status:'received'},delivery:{http_accepted:true,notification:'UNKNOWN',remediation:'NOT_CONFIRMED'}}]})});await page.getByRole('button',{name:/报告与任务/}).click();const acceptedTask=page.locator('[data-task-id="ui-fixture-accepted"]');await acceptedTask.waitFor();check('controlled_accepted_is_not_notification_sent',(await acceptedTask.innerText()).includes('远端已接收，通知未确认')&&!(await acceptedTask.innerText()).includes('原 mock 已记录模拟发送'));await page.unroute('**/api/actions');await page.getByRole('button',{name:/成本分析/}).click();report.limitations.push('ACCEPTED界面状态使用明确标注的只读API注入样例验证，未伪造真实通知发送。');
 check('console_health',report.console_errors.length===0,JSON.stringify(report.console_errors));
 await page.setViewportSize({width:1366,height:768});await page.route('**/api/analyses',route=>route.abort('failed'));await page.getByLabel('工厂',{exact:true}).selectOption('中药二厂');await page.getByRole('alert').waitFor();check('controlled_network_failure_visible',(await page.getByRole('alert').innerText()).includes('请求失败'));await screenshot('1366_controlled_failure');await page.unroute('**/api/analyses');await page.getByLabel('工厂',{exact:true}).selectOption('中药一厂');await page.locator('.metric').first().waitFor();check('recovery_after_network_failure',await page.getByRole('alert').count()===0);
 await context.tracing.stop({path:path.join(out,'browser_trace.zip')});report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);if(page)await screenshot('failure').catch(()=>{})}finally{if(browser)await browser.close();report.finished_at=new Date().toISOString();await writeFile(path.join(out,'results.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'history.jsonl'),JSON.stringify(report)+'\n',{flag:'a'});console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1}
