import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';import {fileURLToPath} from 'node:url';
process.env.TMPDIR='/tmp';const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const reports=JSON.parse(await readFile(path.join(root,'06_评测/scenario_reports.json'),'utf8'));
const result={at:new Date().toISOString(),status:'RUNNING',scope:'Final frozen artifacts and visible degradation; no generation or sending',checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'/mnt/d/AI_Cache/ms-playwright/chromium-1228/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:1366,height:768}});const page=await context.newPage();page.on('pageerror',e=>result.errors.push(String(e)));
for(const item of reports){const response=await context.request.get('http://127.0.0.1:8765/api/jobs/'+item.job_id);const job=await response.json();for(const format of ['docx','pdf']){const file=await context.request.get('http://127.0.0.1:8765/api/artifacts/'+job.result[format].artifact_id);const bytes=await file.body();const valid=file.status()===200&&(format==='docx'?bytes.subarray(0,2).toString()==='PK':bytes.subarray(0,4).toString()==='%PDF');result.checks.push({name:item.scenario+'_'+format,status:valid?'PASS':'FAIL',bytes:bytes.length});}}
const invalid=await context.request.get('http://127.0.0.1:8765/api/artifacts/bd4b5f4acd294d749efd1b947efcb6ea-docx');result.checks.push({name:'invalidated_artifact_rejected',status:invalid.status()===404?'PASS':'FAIL'});
await page.goto('http://127.0.0.1:8765',{waitUntil:'networkidle'});await page.getByLabel('产品',{exact:true}).selectOption('板蓝根颗粒');await page.getByLabel('月份',{exact:true}).selectOption('2026-05');await page.getByRole('button',{name:/报告与任务/}).click();await page.getByText('DEGRADED',{exact:false}).first().waitFor({timeout:15000});await page.screenshot({path:path.join(root,'06_评测/browser_final_reports.png'),fullPage:true});result.checks.push({name:'degraded_report_visible',status:'PASS'});result.status=result.checks.every(x=>x.status==='PASS')&&result.errors.length===0?'PASS':'FAIL';
}catch(e){result.status='FAIL';result.errors.push(String(e));}finally{await browser.close();await writeFile(path.join(root,'06_评测/browser_final_artifacts.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.status!=='PASS')process.exitCode=1;}
