import {useEffect,useState} from 'react';
import {api,contextQuery} from './api';
import {AnalysisStatus,DeveloperDetails,cleanText} from './presentation';
export const findingLabel=(kind:string)=>({numeric_fact:'数值事实',document_fact:'文档事实',hypothesis:'待核查假设',insufficient_evidence:'证据不足',recommendation:'改进建议'}[kind]??kind);
export function snapshotReport(jobs:any[],snapshotId?:string){return jobs.find(j=>j.result?.snapshot?.snapshot_id===snapshotId&&['SUCCEEDED','DEGRADED'].includes(j.status)&&j.result?.narrative);}
export default function NarrativePanel({snapshot,onEvidence}:{snapshot:any;onEvidence:(value:any)=>void}){
 const [submitting,setSubmitting]=useState(false);
 const [report,setReport]=useState<any>(null),[pending,setPending]=useState<string|null>(null),[stage,setStage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setReport(null);setPending(null);setError('');api(`/jobs?${contextQuery(snapshot.context_id??'')}`,undefined,c.signal).then(response=>{const jobs=Array.isArray(response)?response:response.jobs??[];setReport(snapshotReport(jobs,snapshot.snapshot_id));const active=jobs.find((j:any)=>(j.input?.snapshot_id===snapshot.snapshot_id||j.result?.snapshot?.snapshot_id===snapshot.snapshot_id)&&!['SUCCEEDED','DEGRADED','FAILED'].includes(j.status));if(active)setPending(active.id);else if(snapshot.focus?.job_id&&!['FAILED'].includes(snapshot.focus.model_status))setPending(snapshot.focus.job_id);}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort();},[snapshot.snapshot_id]);
 useEffect(()=>{if(!pending)return;const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const job=await api(`/jobs/${encodeURIComponent(pending)}`,undefined,c.signal);if(c.signal.aborted)return;setStage(job.stage);if(['SUCCEEDED','DEGRADED'].includes(job.status)){setReport(job);setPending(null);return;}if(job.status==='FAILED'){setError(job.error??'报告生成失败');setPending(null);return;}timer=setTimeout(poll,2000);}catch(e){if(!c.signal.aborted){setError(e instanceof Error?e.message:String(e));setPending(null);}}};void poll();return()=>{c.abort();clearTimeout(timer)};},[pending]);
 async function generate(retry=false){setSubmitting(true);setError('');setStage('提交中');try{const result=await api('/reports',{context_id:snapshot.context_id,factory:snapshot.factory,product:snapshot.product,month:snapshot.month,analysis_type:snapshot.analysis_type,basis:snapshot.basis,topic:snapshot.topic,...(retry?{retry:true}:{})});setPending(result.job_id);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSubmitting(false)}}
 const narrative=report?.result?.narrative,evidence=report?.result?.evidence?.evidence??[];
 return <section className="panel narrative-panel"><div className="panel-heading"><h2>成本解释与建议</h2><div className="button-row">{!narrative&&<button className="primary" disabled={Boolean(pending)||submitting} onClick={()=>generate()}>{pending||submitting?'生成中…':'生成分析报告'}</button>}{narrative?.status==='DEGRADED'&&<button disabled={Boolean(pending)||submitting} onClick={()=>generate(true)}>{pending||submitting?'重新生成中…':'重新生成（忽略缓存）'}</button>}</div></div>{!narrative&&<p className="muted">生成分析报告后展示与当前快照一致的解释和建议。数字由程序绑定，原因假设必须具备证据与缺证项。</p>}{pending&&<p role="status">报告阶段：{stage||'排队中'}；完成后可在此与“分析报告”页查看下载。</p>}{error&&<p className="error" role="alert">{error}</p>}{narrative&&<><AnalysisStatus narrative={narrative} review={report.result?.acceptance}/>{narrative.findings?.map((f:any,i:number)=>{const body=cleanText(f.rendered_text??f.text_template);return <article className="finding" key={i}><div className="finding-head"><strong>{findingLabel(f.claim_type)}</strong><button className="finding-evidence-btn" aria-label={`查看第${i+1}条${findingLabel(f.claim_type)}的证据依据`} onClick={()=>onEvidence({...f,evidence:evidence.filter((e:any)=>f.evidence_refs?.includes(e.evidence_id)),snapshot_id:snapshot.snapshot_id})}>查看证据依据</button></div><p>{body}</p>{f.missing_evidence?.length>0&&<p className="muted">缺少证据：{f.missing_evidence.join('；')}</p>}{f.suggestion&&cleanText(f.suggestion)!==body&&<p className="finding-suggestion">建议：{f.suggestion}</p>}</article>;})}<DeveloperDetails value={{narrative,evidence,report_status:report.status}}/></>}</section>;
}
