/** Independent synthetic API fixtures; this verifies browser contracts, not backend/model quality. */
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.PHARMA_E2E_URL??'http://127.0.0.1:5178';
const out=process.env.PHARMA_E2E_OUT??'/tmp/yaoheng-context-ui';
const executablePath=process.env.PHARMA_CHROME_PATH; // Otherwise use Playwright's locally installed browser.
await mkdir(out,{recursive:true});
const contexts=[['mechanical_demo','机械参考包','demo-a','合成机械企业'],['chemical_demo','化工参考包','demo-b','合成化工企业']].map(([industry_id,industry_name,company_id,company_name])=>({industry_id,industry_name,company_id,company_name,context_id:`${industry_id}:${company_id}`,data_label:'独立合成演示',capabilities:{wip:{label:'在制品核算',status:'UNAVAILABLE',reason:'未提供在制品事实'}}}));
const requests=[],errors=[],checks=[];let ownerConfirmation=null;
const demoAction=id=>({id:'synthetic-task',status:'SENT',metadata:{snapshot_id:`${id}:2026-06`},payload:{task_title:'合成测试核查任务',assignee:{name:'待分配',department:'合成部门'},source:{finding:'合成核查'},action_details:{expected_evidence:['合成工单']}},delivery:{notification:'SIMULATED_SENT'},responsibility_confirmation:ownerConfirmation});
const snapshot=(context_id,selection={})=>{const chemical=context_id.startsWith('chemical');const unit=chemical?'kg':'件';const value=chemical?'73.25':'17.50';return {snapshot_id:`${context_id}:${selection.month??'2026-06'}`,context_id,product:'同 ID 产品',factory:selection.factory??'甲工厂',month:selection.month??'2026-06',analysis_type:selection.analysis_type??'monthly',basis:selection.basis??'unit',period:{start:'2026-04',end:selection.month??'2026-06'},currency:'元',quantity_unit:unit,metrics:{unit_cost:{value,unit:`元/${unit}`},total_cost:{value:'17500',unit:'元'},quantity:{value:'1000',unit},mom:{value:'25'},yoy:{value:null,reason:'缺少同期'},budget:{value:null,reason:'缺少预算'}},elements:[{key:'processing',name:chemical?'反应加工':'机时加工',unit:value,total:'17500',unit_mom:'25',total_mom:'25',alerts:{unit:true,total:true}}],trend:[{month:'2026-05',unit_cost:'14',total_cost:'14000',quantity:'1000'},{month:'2026-06',unit_cost:value,total_cost:'17500',quantity:'1000'}],details:{available:false,reason:'合成样例未提供物料采购明细'},capabilities:contexts[chemical?1:0].capabilities};};
const browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-CN'});
 await context.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url()),body=request.postDataJSON(),id=body?.context_id??url.searchParams.get('context_id');requests.push({path:url.pathname,query:Object.fromEntries(url.searchParams),body});let data;
 if(url.pathname==='/api/industry/catalog')data={contexts,default_context_id:contexts[0].context_id};
 else if(url.pathname==='/api/catalog')data={products:['同 ID 产品'],factories:['甲工厂','乙工厂','丙工厂'],months:['2026-04','2026-05','2026-06'],context_id:id,capabilities:contexts.find(c=>c.context_id===id)?.capabilities};
 else if(url.pathname==='/api/analyses'){if(id.startsWith('chemical'))await new Promise(r=>setTimeout(r,180));data=snapshot(id,body)}
 else if(url.pathname==='/api/benchmarks')data={product:'同 ID 产品',month:url.searchParams.get('month'),left:url.searchParams.get('left'),right:url.searchParams.get('right'),quantity_unit:id.startsWith('chemical')?'kg':'件',summary:[{name:'单位成本',unit:'元/件',left:'17.50',right:'16.00',delta:'1.50',rate:'9.375'}],elements:[{key:'processing',name:'加工成本',left:'17.50',right:'16.00',delta:'1.50',rate:'9.375',contribution:'100'}],details:{left:{available:false},right:{available:false}},hypotheses:[]};
 else if(url.pathname==='/api/jobs')data=[];
 else if(url.pathname==='/api/actions')data=id===contexts[0].context_id?[demoAction(id)]:[];
 else if(url.pathname==='/api/actions/synthetic-task/acknowledge'){ownerConfirmation={status:'CONFIRMED',confirmed_by:body.confirmed_by,confirmed_at:'2026-01-01T00:00:00Z'};data=demoAction(contexts[0].context_id);}
 else if(url.pathname==='/api/kb')data={status:'PASS',sources:{}};
 else if(url.pathname==='/api/kb/search')data={status:'PASS',evidence:[{evidence_id:`${id}:e1`,source_file:`${id.startsWith('chemical')?'化工':'机械'}合成记录.txt`,products:['同 ID 产品'],location:'合成段落 1'}]};
 else if(url.pathname==='/api/reports')data={job_id:'synthetic-job'};
 else data={status:'RUNNING',stage:'合成响应，仅验证提交合同'};
 try{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})}catch(e){if(!request.failure()?.errorText.includes('ERR_ABORTED'))throw e}
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto(base);await page.locator('.metric').first().getByText('17.50',{exact:false}).waitFor();assert.match(await page.title(),/药衡智析/);checks.push('page identity and meaningful metrics');assert.equal(await page.locator('vite-error-overlay').count(),0);
 await page.getByLabel('行业包').selectOption('chemical_demo');await page.locator('.metric').first().getByText('73.25',{exact:false}).waitFor();assert.match(await page.locator('.snapshot-line').innerText(),/kg/);checks.push('context changes data and units');
 await page.getByLabel('行业包').selectOption('mechanical_demo');await page.locator('.metric').first().getByText('17.50',{exact:false}).waitFor();await page.getByLabel('行业包').selectOption('chemical_demo');await page.getByLabel('行业包').selectOption('mechanical_demo');await page.locator('.metric').first().getByText('17.50',{exact:false}).waitFor();await page.waitForTimeout(300);assert.doesNotMatch(await page.locator('.metrics').innerText(),/73\.25/);checks.push('A → B → A discards delayed responses');
 await page.getByLabel('报告范围').selectOption('quarterly');await page.getByRole('button',{name:/跨厂对标/}).click();await page.getByRole('heading',{name:/差异总览/}).waitFor();await page.getByLabel('基准工厂',{exact:true}).selectOption('丙工厂');await page.waitForResponse(r=>r.url().includes('/benchmarks?')&&r.url().includes(encodeURIComponent('丙工厂')));await page.getByRole('heading',{name:/差异总览/}).waitFor();const benchmark=requests.filter(r=>r.path==='/api/benchmarks').at(-1);assert.equal(benchmark.query.analysis_type,'quarterly');assert.equal(benchmark.query.right,'丙工厂');assert.equal(benchmark.query.context_id,contexts[0].context_id);checks.push('quarterly benchmark and arbitrary factory pair');await page.screenshot({path:`${out}/benchmark-stable.png`,fullPage:true});
 await page.getByRole('button',{name:/数据与证据/}).click();await page.getByRole('button',{name:'检索证据',exact:true}).click();await page.getByText('机械合成记录.txt',{exact:false}).waitFor();assert.equal(requests.filter(r=>r.path==='/api/kb/search').at(-1).body.context_id,contexts[0].context_id);checks.push('knowledge scope carries immutable context');
 await page.getByRole('button',{name:/报告与任务/}).click();await page.getByRole('heading',{name:'当前企业任务看板'}).waitFor();await page.getByRole('button',{name:'生成报告',exact:true}).click();await page.getByText('报告已提交，请查看当前报告的分项验收。').waitFor();assert.equal(requests.filter(r=>r.path==='/api/reports').at(-1).body.context_id,contexts[0].context_id);checks.push('report submits fixed context; task summary distinguishes delivery and owner confirmation');await page.getByRole('button',{name:'登记责任人确认',exact:true}).click();assert.equal(await page.getByLabel('责任确认人姓名').inputValue(),'');assert.equal(await page.getByRole('button',{name:'确认本人将跟进'}).isDisabled(),true);await page.getByLabel('责任确认人姓名').fill('合成测试签名');await page.getByRole('button',{name:'确认本人将跟进'}).click();await page.getByText('责任人确认：合成测试签名',{exact:false}).waitFor();assert.equal(await page.locator('.task-summary>div').nth(2).locator('strong').innerText(),'1');checks.push('manual owner confirmation starts blank and updates a separate signed confirmation count (mock only)');
 const second=await context.newPage();await second.goto(base);await second.getByLabel('行业包').selectOption('chemical_demo');await second.locator('.metric').first().getByText('73.25',{exact:false}).waitFor();assert.equal(await page.getByLabel('行业包').inputValue(),'mechanical_demo');checks.push('concurrent browser sessions keep independent selected contexts');
 await page.getByRole('button',{name:/成本分析/}).click();await page.getByRole('img',{name:'成本要素环比热力图'}).waitFor();await page.screenshot({path:`${out}/desktop-analysis.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/mobile-analysis.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('desktop/mobile no horizontal overflow; heatmap rendered');assert.deepEqual(errors,[]);checks.push('no runtime/console errors');
 await writeFile(`${out}/qa.json`,JSON.stringify({status:'PASS',scope:'synthetic mocked API browser contracts only',browser_plugin:'Browser plugin not available; regular Playwright',url:base,checks,console_errors:errors},null,2));console.log(JSON.stringify({status:'PASS',checks,out}));
}finally{await browser.close()}
