/**
 * ⚠ 已废弃（2026-09-24 审计 AUD-FE-02）：本脚本的选择器基于三模块改版（2026-09-22）之前的
 * 界面结构，当前 UI 下首步即超时。保留仅作历史演示物料溯源，不再作为回归入口；
 * 现行可用脚本见 e2e-dashboard.mjs / e2e-knowledge-graph.mjs / record_demo_20260918.mjs。
 */
/** Live API/UI smoke for independently authored public reference packs. No mocked network. */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.PHARMA_E2E_URL??'http://127.0.0.1:8765',out=process.env.PHARMA_E2E_OUT??'/tmp/yaoheng-live-ui';
await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.PHARMA_CHROME_PATH,headless:true,args:['--no-sandbox']});
const checks=[],errors=[],apiFailures=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-CN'}),page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)apiFailures.push({url:r.url(),status:r.status()})});
 await page.goto(`${base}/?context_id=mechanical_demo:synthetic-mechanical`);await page.getByLabel('行业包').selectOption('mechanical_demo');await page.locator('.metric').first().getByText('30.00',{exact:false}).waitFor({timeout:30000});assert.match(await page.locator('.snapshot-line').innerText(),/件/);assert.match(await page.locator('body').innerText(),/单位机时/);assert.match(await page.locator('body').innerText(),/0\.5/);checks.push('mechanical monthly: independent expected unit cost 30, unit machine hours 0.5');
 await page.getByLabel('报告范围').selectOption('quarterly');await page.locator('.metric').first().getByText('29.38',{exact:false}).waitFor();checks.push('mechanical quarter: independent 9400 / 320 = 29.375, displayed 29.38');
 await page.getByRole('button',{name:/跨厂对标/}).click();await page.getByRole('heading',{name:/差异总览/}).waitFor({timeout:120000});assert.match(await page.locator('main').innerText(),/季度/);assert.doesNotMatch(await page.locator('main').innerText(),/元\/盒/);await page.getByRole('button',{name:'交换工厂方向'}).click();await page.getByRole('heading',{name:/差异总览/}).waitFor({timeout:120000});assert.equal(await page.locator('.loading').count(),0);await page.screenshot({path:`${out}/benchmark-real-stable.png`,fullPage:true});checks.push('real quarterly benchmark both directions, stable table and chart before screenshot');
 await page.getByRole('button',{name:/成本分析/}).click();await page.getByLabel('行业包').selectOption('chemical_demo');await page.locator('.metric').first().getByText('12.00',{exact:false}).waitFor();assert.match(await page.locator('.snapshot-line').innerText(),/kg/);assert.match(await page.locator('body').innerText(),/单位能耗/);checks.push('chemical switch resets legal filters; monthly cost 12 and energy metric present');
 await page.getByRole('button',{name:/数据与证据/}).click();await page.getByLabel('知识检索问题').fill('批次 能耗');await page.getByRole('button',{name:'检索证据',exact:true}).click();await page.locator('.evidence-result').first().waitFor({timeout:30000});assert.doesNotMatch(await page.locator('.evidence-result').first().innerText(),/机械/);checks.push('chemical knowledge retrieval rendered in its own context');
 await page.getByRole('button',{name:/成本分析/}).click();await page.getByLabel('行业包').selectOption('mechanical_demo');await page.locator('.metric').first().getByText('30.00',{exact:false}).waitFor();assert.doesNotMatch(await page.locator('.metrics').innerText(),/12\.00/);checks.push('real A → B → A restores context correctly');
 await page.getByRole('img',{name:'成本要素环比热力图'}).waitFor();await page.screenshot({path:`${out}/mechanical-desktop.png`,fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth,{},{timeout:3000}).catch(async e=>{await page.screenshot({path:`${out}/mobile-overflow.png`,fullPage:true});console.log(await page.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,text:e.innerText?.slice(0,80)}))));throw e});await page.screenshot({path:`${out}/mechanical-mobile.png`,fullPage:true});checks.push('real heatmap, desktop and mobile rendered without horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:/报告与任务/}).click();await page.getByRole('heading',{name:'当前企业任务看板'}).waitFor();const reportPromise=page.waitForResponse(r=>r.url().endsWith('/api/reports')&&r.request().method()==='POST');await page.getByRole('button',{name:'生成报告',exact:true}).click();const job=await(await reportPromise).json();assert.ok(job.job_id);checks.push('real report job submitted in mechanical context');
 assert.deepEqual(errors,[]);assert.deepEqual(apiFailures,[]);assert.equal(await page.locator('vite-error-overlay').count(),0);
 await writeFile(`${out}/qa.json`,JSON.stringify({status:'PASS',scope:'live public reference-pack UI and API; report submission only, final files/model/RPA not asserted',url:base,viewports:['1440x1000','390x844'],checks,errors,apiFailures,submitted_job:job.job_id},null,2));console.log(JSON.stringify({status:'PASS',checks,job:job.job_id,out}));
}catch(e){await writeFile(`${out}/failure.json`,JSON.stringify({error:String(e),checks,errors,apiFailures},null,2));throw e}finally{await browser.close()}
