import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
process.env.TMPDIR='/tmp';const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'06_评测');
const report={created_at:new Date().toISOString(),status:'RUNNING',checks:[],console_errors:[]};
const browser=await chromium.launch({executablePath:'/mnt/d/AI_Cache/ms-playwright/chromium-1228/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1366,height:768},locale:'zh-CN'});const page=await context.newPage();page.on('pageerror',e=>report.console_errors.push(String(e)));
const check=(name,ok)=>{report.checks.push({name,status:ok?'PASS':'FAIL'});if(!ok)throw Error(name)};
try{
 await page.goto('http://127.0.0.1:8765',{waitUntil:'networkidle'});await page.getByLabel('报告范围').selectOption('quarterly');await page.getByText('11.02',{exact:false}).first().waitFor();check('quarter_explicit_end_month',await page.getByLabel('月份',{exact:true}).inputValue()==='2026-06');check('quarter_weighted_display',(await page.locator('.metric').first().innerText()).includes('11.02'));check('quarter_quantity_golden',(await page.locator('.snapshot-line').innerText()).includes('163,000'));await page.screenshot({path:path.join(out,'browser_quarter.png'),fullPage:false});
 await page.getByLabel('报告范围').selectOption('monthly');await page.getByLabel('产品',{exact:true}).selectOption('六味地黄胶囊');await page.getByLabel('月份',{exact:true}).selectOption('2026-03');await page.getByRole('button',{name:/报告与任务/}).click();const list=await(await context.request.get('http://127.0.0.1:8765/api/actions')).json();const old=list.find(a=>a.payload.source.finding.startsWith('2026年3月六味地黄胶囊单位成本下降、总额上升；设备停机事件仅支持待核查假设，不证明净因果。'));if(!old)throw Error('Expected earlier confirmed fixture absent');const row=page.locator('.task').filter({hasText:old.id});await row.getByRole('button',{name:'查询原 mock 远端状态'}).click();await row.getByText('本地 REMOTE_UNKNOWN',{exact:false}).waitFor({timeout:20000});check('remote_restart_unknown_visible',true);const after=await(await context.request.get('http://127.0.0.1:8765/api/actions/'+old.id)).json();check('remote_restart_no_recreate',after.status==='REMOTE_UNKNOWN');check('old_payload_id_preserved',after.payload.task_id===old.id);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'browser_tasks.png'),fullPage:true});check('console_health',report.console_errors.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);}finally{await browser.close();await writeFile(path.join(out,'browser_recovery_results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
